class Bank {
    static int bankId ;
    static String bankName; 
    static String location ;
    static String branchCode; 
    static boolean isNationalized; 
    static float interestRate;
    static double balance;
    static char code ;
    static short atmCount; 
    static long ifsc ;
    static String managerName; 
    static int employees ;
    static String country ;
    static boolean hasLoanFacility ;
    static String currency ;
    static double minBalance; 
    static int foundedYear ;
    static String email ;
    static boolean mobileBanking; 
    static String bankType ;

    public static void main(String bank[]) {
        System.out.println("Bank ID: " + bankId);
        System.out.println("Bank Name: " + bankName);
        System.out.println("Location: " + location);
        System.out.println("Branch Code: " + branchCode);
        System.out.println("Is Nationalized: " + isNationalized);
        System.out.println("Interest Rate: " + interestRate);
        System.out.println("Balance: " + balance);
        System.out.println("Code: " + code);
        System.out.println("ATM Count: " + atmCount);
        System.out.println("IFSC: " + ifsc);
        System.out.println("Manager Name: " + managerName);
        System.out.println("Employees: " + employees);
        System.out.println("Country: " + country);
        System.out.println("Loan Facility Available: " + hasLoanFacility);
        System.out.println("Currency: " + currency);
        System.out.println("Minimum Balance: " + minBalance);
        System.out.println("Founded Year: " + foundedYear);
        System.out.println("Email: " + email);
        System.out.println("Mobile Banking: " + mobileBanking);
        System.out.println("Bank Type: " + bankType);
		
		bankId=1;
		bankName = "Canara Bank";
		location = "Bangalore";
		branchCode = "CNB110";
		isNationalized = true;
        interestRate = 4.5f;
        balance = 250000.75;
        code = 'C';
		atmCount = 12;
		ifsc = 1234567890L;
		managerName = "Anjali";
		employees = 50;
		country = "India";
		hasLoanFacility = true;
		currency = "INR";
		minBalance = 1000.00;
		foundedYear = 1906;
		email = "help@canarabank.in";
		mobileBanking = true;
		bankType = "Public";
		 System.out.println("Bank ID: " + bankId);
        System.out.println("Bank Name: " + bankName);
        System.out.println("Location: " + location);
        System.out.println("Branch Code: " + branchCode);
        System.out.println("Is Nationalized: " + isNationalized);
        System.out.println("Interest Rate: " + interestRate);
        System.out.println("Balance: " + balance);
        System.out.println("Code: " + code);
        System.out.println("ATM Count: " + atmCount);
        System.out.println("IFSC: " + ifsc);
        System.out.println("Manager Name: " + managerName);
        System.out.println("Employees: " + employees);
        System.out.println("Country: " + country);
        System.out.println("Loan Facility Available: " + hasLoanFacility);
        System.out.println("Currency: " + currency);
        System.out.println("Minimum Balance: " + minBalance);
        System.out.println("Founded Year: " + foundedYear);
        System.out.println("Email: " + email);
        System.out.println("Mobile Banking: " + mobileBanking);
        System.out.println("Bank Type: " + bankType);
    }
}