class CasinoRunner{
public sttaic void main(String[] casi){

System.out.println("main started");
Casino casino1 = new Casino();
casino1.casinoId = 101;
casino1.name = "Royal Flush";
casino1.location = "Las Vegas";
casino1.numberOfGames = 200;
casino1.revenue = 150.5;
casino1.isOpen24Hours = true;
casino1.managerName = "John Doe";
casino1.areaInSqFt = 50000;
casino1.employeeCount = 300;
casino1.specialtyGame = "Poker";
System.out.println("Casino 1:");
System.out.println("Casino ID: " + casino1.casinoId);
System.out.println("Name: " + casino1.name);
System.out.println("Location: " + casino1.location);
System.out.println("Number of Games: " + casino1.numberOfGames);
System.out.println("Revenue (million): " + casino1.revenue);
System.out.println("Open 24 Hours: " + casino1.isOpen24Hours);
System.out.println("Manager Name: " + casino1.managerName);
System.out.println("Area (sq ft): " + casino1.areaInSqFt);
System.out.println("Employee Count: " + casino1.employeeCount);
System.out.println("Specialty Game: " + casino1.specialtyGame);
System.out.println();

Casino casino2 = new Casino();
casino2.casinoId = 102;
casino2.name = "Lucky Star";
casino2.location = "Macau";
casino2.numberOfGames = 250;
casino2.revenue = 200.75;
casino2.isOpen24Hours = false;
casino2.managerName = "Alice Smith";
casino2.areaInSqFt = 60000;
casino2.employeeCount = 350;
casino2.specialtyGame = "Blackjack";
System.out.println("Casino 2:");
System.out.println("Casino ID: " + casino2.casinoId);
System.out.println("Name: " + casino2.name);
System.out.println("Location: " + casino2.location);
System.out.println("Number of Games: " + casino2.numberOfGames);
System.out.println("Revenue (million): " + casino2.revenue);
System.out.println("Open 24 Hours: " + casino2.isOpen24Hours);
System.out.println("Manager Name: " + casino2.managerName);
System.out.println("Area (sq ft): " + casino2.areaInSqFt);
System.out.println("Employee Count: " + casino2.employeeCount);
System.out.println("Specialty Game: " + casino2.specialtyGame);
System.out.println();

Casino casino3 = new Casino();
casino3.casinoId = 103;
casino3.name = "Golden Palace";
casino3.location = "Atlantic City";
casino3.numberOfGames = 180;
casino3.revenue = 120.0;
casino3.isOpen24Hours = true;
casino3.managerName = "Robert Brown";
casino3.areaInSqFt = 45000;
casino3.employeeCount = 280;
casino3.specialtyGame = "Roulette";
System.out.println("Casino 3:");
System.out.println("Casino ID: " + casino3.casinoId);
System.out.println("Name: " + casino3.name);
System.out.println("Location: " + casino3.location);
System.out.println("Number of Games: " + casino3.numberOfGames);
System.out.println("Revenue (million): " + casino3.revenue);
System.out.println("Open 24 Hours: " + casino3.isOpen24Hours);
System.out.println("Manager Name: " + casino3.managerName);
System.out.println("Area (sq ft): " + casino3.areaInSqFt);
System.out.println("Employee Count: " + casino3.employeeCount);
System.out.println("Specialty Game: " + casino3.specialtyGame);
System.out.println();

Casino casino4 = new Casino();
casino4.casinoId = 104;
casino4.name = "Silver Sands";
casino4.location = "Monaco";
casino4.numberOfGames = 150;
casino4.revenue = 90.3;
casino4.isOpen24Hours = false;
casino4.managerName = "Linda Green";
casino4.areaInSqFt = 40000;
casino4.employeeCount = 220;
casino4.specialtyGame = "Baccarat";
System.out.println("Casino 4:");
System.out.println("Casino ID: " + casino4.casinoId);
System.out.println("Name: " + casino4.name);
System.out.println("Location: " + casino4.location);
System.out.println("Number of Games: " + casino4.numberOfGames);
System.out.println("Revenue (million): " + casino4.revenue);
System.out.println("Open 24 Hours: " + casino4.isOpen24Hours);
System.out.println("Manager Name: " + casino4.managerName);
System.out.println("Area (sq ft): " + casino4.areaInSqFt);
System.out.println("Employee Count: " + casino4.employeeCount);
System.out.println("Specialty Game: " + casino4.specialtyGame);
System.out.println();

Casino casino5 = new Casino();
casino5.casinoId = 105;
casino5.name = "Emerald Bay";
casino5.location = "Singapore";
casino5.numberOfGames = 220;
casino5.revenue = 175.8;
casino5.isOpen24Hours = true;
casino5.managerName = "Michael Lee";
casino5.areaInSqFt = 55000;
casino5.employeeCount = 310;
casino5.specialtyGame = "Slots";
System.out.println("Casino 5:");
System.out.println("Casino ID: " + casino5.casinoId);
System.out.println("Name: " + casino5.name);
System.out.println("Location: " + casino5.location);
System.out.println("Number of Games: " + casino5.numberOfGames);
System.out.println("Revenue (million): " + casino5.revenue);
System.out.println("Open 24 Hours: " + casino5.isOpen24Hours);
System.out.println("Manager Name: " + casino5.managerName);
System.out.println("Area (sq ft): " + casino5.areaInSqFt);
System.out.println("Employee Count: " + casino5.employeeCount);
System.out.println("Specialty Game: " + casino5.specialtyGame);
System.out.println();

Casino casino6 = new Casino();
casino6.casinoId = 106;
casino6.name = "The Mirage";
casino6.location = "Las Vegas";
casino6.numberOfGames = 230;
casino6.revenue = 160.0;
casino6.isOpen24Hours = true;
casino6.managerName = "Emma Watson";
casino6.areaInSqFt = 57000;
casino6.employeeCount = 320;
casino6.specialtyGame = "Poker";
System.out.println("Casino 6:");
System.out.println("Casino ID: " + casino6.casinoId);
System.out.println("Name: " + casino6.name);
System.out.println("Location: " + casino6.location);
System.out.println("Number of Games: " + casino6.numberOfGames);
System.out.println("Revenue (million): " + casino6.revenue);
System.out.println("Open 24 Hours: " + casino6.isOpen24Hours);
System.out.println("Manager Name: " + casino6.managerName);
System.out.println("Area (sq ft): " + casino6.areaInSqFt);
System.out.println("Employee Count: " + casino6.employeeCount);
System.out.println("Specialty Game: " + casino6.specialtyGame);
System.out.println();

Casino casino7 = new Casino();
casino7.casinoId = 107;
casino7.name = "High Roller";
casino7.location = "Atlantic City";
casino7.numberOfGames = 190;
casino7.revenue = 130.4;
casino7.isOpen24Hours = false;
casino7.managerName = "David Johnson";
casino7.areaInSqFt = 46000;
casino7.employeeCount = 290;
casino7.specialtyGame = "Roulette";
System.out.println("Casino 7:");
System.out.println("Casino ID: " + casino7.casinoId);
System.out.println("Name: " + casino7.name);
System.out.println("Location: " + casino7.location);
System.out.println("Number of Games: " + casino7.numberOfGames);
System.out.println("Revenue (million): " + casino7.revenue);
System.out.println("Open 24 Hours: " + casino7.isOpen24Hours);
System.out.println("Manager Name: " + casino7.managerName);
System.out.println("Area (sq ft): " + casino7.areaInSqFt);
System.out.println("Employee Count: " + casino7.employeeCount);
System.out.println("Specialty Game: " + casino7.specialtyGame);
System.out.println();

Casino casino8 = new Casino();
casino8.casinoId = 108;
casino8.name = "Jackpot City";
casino8.location = "Monaco";
casino8.numberOfGames = 210;
casino8.revenue = 140.2;
casino8.isOpen24Hours = true;
casino8.managerName = "Sophie Turner";
casino8.areaInSqFt = 52000;
casino8.employeeCount = 330;
casino8.specialtyGame = "Baccarat";
System.out.println("Casino 8:");
System.out.println("Casino ID: " + casino8.casinoId);
System.out.println("Name: " + casino8.name);
System.out.println("Location: " + casino8.location);
System.out.println("Number of Games: " + casino8.numberOfGames);
System.out.println("Revenue (million): " + casino8.revenue);
System.out.println("Open 24 Hours: " + casino8.isOpen24Hours);
System.out.println("Manager Name: " + casino8.managerName);
System.out.println("Area (sq ft): " + casino8.areaInSqFt);
System.out.println("Employee Count: " + casino8.employeeCount);
System.out.println("Specialty Game: " + casino8.specialtyGame);
System.out.println();

Casino casino9 = new Casino();
casino9.casinoId = 109;
casino9.name = "Diamond Lounge";
casino9.location = "Singapore";
casino9.numberOfGames = 240;
casino9.revenue = 190.1;
casino9.isOpen24Hours = false;
casino9.managerName = "Chris Evans";
casino9.areaInSqFt = 58000;
casino9.employeeCount = 340;
casino9.specialtyGame = "Slots";
System.out.println("Casino 9:");
System.out.println("Casino ID: " + casino9.casinoId);
System.out.println("Name: " + casino9.name);
System.out.println("Location: " + casino9.location);
System.out.println("Number of Games: " + casino9.numberOfGames);
System.out.println("Revenue (million): " + casino9.revenue);
System.out.println("Open 24 Hours: " + casino9.isOpen24Hours);
System.out.println("Manager Name: " + casino9.managerName);
System.out.println("Area (sq ft): " + casino9.areaInSqFt);
System.out.println("Employee Count: " + casino9.employeeCount);
System.out.println("Specialty Game: " + casino9.specialtyGame);
System.out.println();

Casino casino10 = new Casino();
casino10.casinoId = 110;
casino10.name = "Casino Royale";
casino10.location = "Las Vegas";
casino10.numberOfGames = 260;
casino10.revenue = 210.0;
casino10.isOpen24Hours = true;
casino10.managerName = "Daniel Craig";
casino10.areaInSqFt = 62000;
casino10.employeeCount = 360;
casino10.specialtyGame = "Poker";
System.out.println("Casino 10:");
System.out.println("Casino ID: " + casino10.casinoId);
System.out.println("Name: " + casino10.name);
System.out.println("Location: " + casino10.location);
System.out.println("Number of Games: " + casino10.numberOfGames);
System.out.println("Revenue (million): " + casino10.revenue);
System.out.println("Open 24 Hours: " + casino10.isOpen24Hours);
System.out.println("Manager Name: " + casino10.managerName);
System.out.println("Area (sq ft): " + casino10.areaInSqFt);
System.out.println("Employee Count: " + casino10.employeeCount);
System.out.println("Specialty Game: " + casino10.specialtyGame);
System.out.println();

Casino casino11 = new Casino();
casino11.casinoId = 111;
casino11.name = "Ocean Breeze";
casino11.location = "Macau";
casino11.numberOfGames = 170;
casino11.revenue = 100.5;
casino11.isOpen24Hours = false;
casino11.managerName = "Natalie Portman";
casino11.areaInSqFt = 43000;
casino11.employeeCount = 270;
casino11.specialtyGame = "Blackjack";
System.out.println("Casino 11:");
System.out.println("Casino ID: " + casino11.casinoId);
System.out.println("Name: " + casino11.name);
System.out.println("Location: " + casino11.location);
System.out.println("Number of Games: " + casino11.numberOfGames);
System.out.println("Revenue (million): " + casino11.revenue);
System.out.println("Open 24 Hours: " + casino11.isOpen24Hours);
System.out.println("Manager Name: " + casino11.managerName);
System.out.println("Area (sq ft): " + casino11.areaInSqFt);
System.out.println("Employee Count: " + casino11.employeeCount);
System.out.println("Specialty Game: " + casino11.specialtyGame);
System.out.println();

Casino casino12 = new Casino();
casino12.casinoId = 112;
casino12.name = "The Grand";
casino12.location = "Atlantic City";
casino12.numberOfGames = 155;
casino12.revenue = 95.3;
casino12.isOpen24Hours = true;
casino12.managerName = "George Clooney";
casino12.areaInSqFt = 41000;
casino12.employeeCount = 240;
casino12.specialtyGame = "Roulette";
System.out.println("Casino 12:");
System.out.println("Casino ID: " + casino12.casinoId);
System.out.println("Name: " + casino12.name);
System.out.println("Location: " + casino12.location);
System.out.println("Number of Games: " + casino12.numberOfGames);
System.out.println("Revenue (million): " + casino12.revenue);
System.out.println("Open 24 Hours: " + casino12.isOpen24Hours);
System.out.println("Manager Name: " + casino12.managerName);
System.out.println("Area (sq ft): " + casino12.areaInSqFt);
System.out.println("Employee Count: " + casino12.employeeCount);
System.out.println("Specialty Game: " + casino12.specialtyGame);
System.out.println();

Casino casino13 = new Casino();
casino13.casinoId = 113;
casino13.name = "Diamond Club";
casino13.location = "Monaco";
casino13.numberOfGames = 195;
casino13.revenue = 145.7;
casino13.isOpen24Hours = false;
casino13.managerName = "Scarlett Johansson";
casino13.areaInSqFt = 53000;
casino13.employeeCount = 310;
casino13.specialtyGame = "Baccarat";
System.out.println("Casino 13:");
System.out.println("Casino ID: " + casino13.casinoId);
System.out.println("Name: " + casino13.name);
System.out.println("Location: " + casino13.location);
System.out.println("Number of Games: " + casino13.numberOfGames);
System.out.println("Revenue (million): " + casino13.revenue);
System.out.println("Open 24 Hours: " + casino13.isOpen24Hours);
System.out.println("Manager Name: " + casino13.managerName);
System.out.println("Area (sq ft): " + casino13.areaInSqFt);
System.out.println("Employee Count: " + casino13.employeeCount);
System.out.println("Specialty Game: " + casino13.specialtyGame);
System.out.println();

Casino casino14 = new Casino();
casino14.casinoId = 114;
casino14.name = "Sunset Strip";
casino14.location = "Las Vegas";
casino14.numberOfGames = 210;
casino14.revenue = 180.0;
casino14.isOpen24Hours = true;
casino14.managerName = "Tom Hanks";
casino14.areaInSqFt = 56000;
casino14.employeeCount = 340;
casino14.specialtyGame = "Slots";
System.out.println("Casino 14:");
System.out.println("Casino ID: " + casino14.casinoId);
System.out.println("Name: " + casino14.name);
System.out.println("Location: " + casino14.location);
System.out.println("Number of Games: " + casino14.numberOfGames);
System.out.println("Revenue (million): " + casino14.revenue);
System.out.println("Open 24 Hours: " + casino14.isOpen24Hours);
System.out.println("Manager Name: " + casino14.managerName);
System.out.println("Area (sq ft): " + casino14.areaInSqFt);
System.out.println("Employee Count: " + casino14.employeeCount);
System.out.println("Specialty Game: " + casino14.specialtyGame);
System.out.println();

Casino casino15 = new Casino();
casino15.casinoId = 115;
casino15.name = "Majestic";
casino15.location = "Macau";
casino15.numberOfGames = 175;
casino15.revenue = 110.4;
casino15.isOpen24Hours = false;
casino15.managerName = "Emma Stone";
casino15.areaInSqFt = 44000;
casino15.employeeCount = 260;
casino15.specialtyGame = "Blackjack";
System.out.println("Casino 15:");
System.out.println("Casino ID: " + casino15.casinoId);
System.out.println("Name: " + casino15.name);
System.out.println("Location: " + casino15.location);
System.out.println("Number of Games: " + casino15.numberOfGames);
System.out.println("Revenue (million): " + casino15.revenue);
System.out.println("Open 24 Hours: " + casino15.isOpen24Hours);
System.out.println("Manager Name: " + casino15.managerName);
System.out.println("Area (sq ft): " + casino15.areaInSqFt);
System.out.println("Employee Count: " + casino15.employeeCount);
System.out.println("Specialty Game: " + casino15.specialtyGame);
System.out.println();

Casino casino16 = new Casino();
casino16.casinoId = 116;
casino16.name = "Lucky Seven";
casino16.location = "Atlantic City";
casino16.numberOfGames = 185;
casino16.revenue = 135.6;
casino16.isOpen24Hours = true;
casino16.managerName = "Chris Hemsworth";
casino16.areaInSqFt = 47000;
casino16.employeeCount = 300;
casino16.specialtyGame = "Roulette";
System.out.println("Casino 16:");
System.out.println("Casino ID: " + casino16.casinoId);
System.out.println("Name: " + casino16.name);
System.out.println("Location: " + casino16.location);
System.out.println("Number of Games: " + casino16.numberOfGames);
System.out.println("Revenue (million): " + casino16.revenue);
System.out.println("Open 24 Hours: " + casino16.isOpen24Hours);
System.out.println("Manager Name: " + casino16.managerName);
System.out.println("Area (sq ft): " + casino16.areaInSqFt);
System.out.println("Employee Count: " + casino16.employeeCount);
System.out.println("Specialty Game: " + casino16.specialtyGame);
System.out.println();

Casino casino17 = new Casino();
casino17.casinoId = 117;
casino17.name = "The Velvet";
casino17.location = "Monaco";
casino17.numberOfGames = 160;
casino17.revenue = 100.9;
casino17.isOpen24Hours = false;
casino17.managerName = "Jennifer Lawrence";
casino17.areaInSqFt = 42000;
casino17.employeeCount = 250;
casino17.specialtyGame = "Baccarat";
System.out.println("Casino 17:");
System.out.println("Casino ID: " + casino17.casinoId);
System.out.println("Name: " + casino17.name);
System.out.println("Location: " + casino17.location);
System.out.println("Number of Games: " + casino17.numberOfGames);
System.out.println("Revenue (million): " + casino17.revenue);
System.out.println("Open 24 Hours: " + casino17.isOpen24Hours);
System.out.println("Manager Name: " + casino17.managerName);
System.out.println("Area (sq ft): " + casino17.areaInSqFt);
System.out.println("Employee Count: " + casino17.employeeCount);
System.out.println("Specialty Game: " + casino17.specialtyGame);
System.out.println();

Casino casino18 = new Casino();
casino18.casinoId = 118;
casino18.name = "Crystal Palace";
casino18.location = "Las Vegas";
casino18.numberOfGames = 220;
casino18.revenue = 170.0;
casino18.isOpen24Hours = true;
casino18.managerName = "Leonardo DiCaprio";
casino18.areaInSqFt = 54000;
casino18.employeeCount = 320;
casino18.specialtyGame = "Slots";
System.out.println("Casino 18:");
System.out.println("Casino ID: " + casino18.casinoId);
System.out.println("Name: " + casino18.name);
System.out.println("Location: " + casino18.location);
System.out.println("Number of Games: " + casino18.numberOfGames);
System.out.println("Revenue (million): " + casino18.revenue);
System.out.println("Open 24 Hours: " + casino18.isOpen24Hours);
System.out.println("Manager Name: " + casino18.managerName);
System.out.println("Area (sq ft): " + casino18.areaInSqFt);
System.out.println("Employee Count: " + casino18.employeeCount);
System.out.println("Specialty Game: " + casino18.specialtyGame);
System.out.println();

Casino casino19 = new Casino();
casino19.casinoId = 119;
casino19.name = "The Grand Royale";
casino19.location = "Macau";
casino19.numberOfGames = 210;
casino19.revenue = 160.4;
casino19.isOpen24Hours = false;
casino19.managerName = "Brad Pitt";
casino19.areaInSqFt = 51000;
casino19.employeeCount = 310;
casino19.specialtyGame = "Poker";
System.out.println("Casino 19:");
System.out.println("Casino ID: " + casino19.casinoId);
System.out.println("Name: " + casino19.name);
System.out.println("Location: " + casino19.location);
System.out.println("Number of Games: " + casino19.numberOfGames);
System.out.println("Revenue (million): " + casino19.revenue);
System.out.println("Open 24 Hours: " + casino19.isOpen24Hours);
System.out.println("Manager Name: " + casino19.managerName);
System.out.println("Area (sq ft): " + casino19.areaInSqFt);
System.out.println("Employee Count: " + casino19.employeeCount);
System.out.println("Specialty Game: " + casino19.specialtyGame);
System.out.println();

Casino casino20 = new Casino();
casino20.casinoId = 120;
casino20.name = "Platinum Lounge";
casino20.location = "Atlantic City";
casino20.numberOfGames = 175;
casino20.revenue = 120.7;
casino20.isOpen24Hours = true;
casino20.managerName = "Morgan Freeman";
casino20.areaInSqFt = 46000;
casino20.employeeCount = 280;
casino20.specialtyGame = "Roulette";
System.out.println("Casino 20:");
System.out.println("Casino ID: " + casino20.casinoId);
System.out.println("Name: " + casino20.name);
System.out.println("Location: " + casino20.location);
System.out.println("Number of Games: " + casino20.numberOfGames);
System.out.println("Revenue (million): " + casino20.revenue);
System.out.println("Open 24 Hours: " + casino20.isOpen24Hours);
System.out.println("Manager Name: " + casino20.managerName);
System.out.println("Area (sq ft): " + casino20.areaInSqFt);
System.out.println("Employee Count: " + casino20.employeeCount);
System.out.println("Specialty Game: " + casino20.specialtyGame);
System.out.println();


System.out.println("main ended");


}
}