class CourtCaseRunner{
public static void main(String[] court){

System.out.pritln("main startd");
CourtCase case1 = new CourtCase();
case1.caseId = 201;
case1.caseType = "Criminal";
case1.plaintiff = "State of California";
case1.defendant = "John Doe";
case1.courtName = "Superior Court of California";
case1.judgeName = "Judge Smith";
case1.filingDate = "2024-01-10";
case1.hearingDate = "2024-06-15";
case1.status = "Pending";
case1.caseValue = 0.0;
System.out.println("Case 1: ");
System.out.println("Case ID: " + case1.caseId);
System.out.println("Case Type: " + case1.caseType);
System.out.println("Plaintiff: " + case1.plaintiff);
System.out.println("Defendant: " + case1.defendant);
System.out.println("Court Name: " + case1.courtName);
System.out.println("Judge Name: " + case1.judgeName);
System.out.println("Filing Date: " + case1.filingDate);
System.out.println("Hearing Date: " + case1.hearingDate);
System.out.println("Status: " + case1.status);
System.out.println("Case Value: " + case1.caseValue);
System.out.println();

CourtCase case2 = new CourtCase();
case2.caseId = 202;
case2.caseType = "Civil";
case2.plaintiff = "Jane Smith";
case2.defendant = "ABC Corporation";
case2.courtName = "District Court";
case2.judgeName = "Judge Adams";
case2.filingDate = "2023-12-05";
case2.hearingDate = "2024-04-20";
case2.status = "Ongoing";
case2.caseValue = 150000.00;
System.out.println("Case 2: ");
System.out.println("Case ID: " + case2.caseId);
System.out.println("Case Type: " + case2.caseType);
System.out.println("Plaintiff: " + case2.plaintiff);
System.out.println("Defendant: " + case2.defendant);
System.out.println("Court Name: " + case2.courtName);
System.out.println("Judge Name: " + case2.judgeName);
System.out.println("Filing Date: " + case2.filingDate);
System.out.println("Hearing Date: " + case2.hearingDate);
System.out.println("Status: " + case2.status);
System.out.println("Case Value: " + case2.caseValue);
System.out.println();

CourtCase case3 = new CourtCase();
case3.caseId = 203;
case3.caseType = "Family";
case3.plaintiff = "Alice Johnson";
case3.defendant = "Bob Johnson";
case3.courtName = "Family Court";
case3.judgeName = "Judge Williams";
case3.filingDate = "2024-02-01";
case3.hearingDate = "2024-05-10";
case3.status = "Pending";
case3.caseValue = 0.0;
System.out.println("Case 3: ");
System.out.println("Case ID: " + case3.caseId);
System.out.println("Case Type: " + case3.caseType);
System.out.println("Plaintiff: " + case3.plaintiff);
System.out.println("Defendant: " + case3.defendant);
System.out.println("Court Name: " + case3.courtName);
System.out.println("Judge Name: " + case3.judgeName);
System.out.println("Filing Date: " + case3.filingDate);
System.out.println("Hearing Date: " + case3.hearingDate);
System.out.println("Status: " + case3.status);
System.out.println("Case Value: " + case3.caseValue);
System.out.println();

CourtCase case4 = new CourtCase();
case4.caseId = 204;
case4.caseType = "Criminal";
case4.plaintiff = "State of Texas";
case4.defendant = "Michael Brown";
case4.courtName = "Texas Criminal Court";
case4.judgeName = "Judge Garcia";
case4.filingDate = "2023-11-15";
case4.hearingDate = "2024-03-30";
case4.status = "Ongoing";
case4.caseValue = 0.0;
System.out.println("Case 4: ");
System.out.println("Case ID: " + case4.caseId);
System.out.println("Case Type: " + case4.caseType);
System.out.println("Plaintiff: " + case4.plaintiff);
System.out.println("Defendant: " + case4.defendant);
System.out.println("Court Name: " + case4.courtName);
System.out.println("Judge Name: " + case4.judgeName);
System.out.println("Filing Date: " + case4.filingDate);
System.out.println("Hearing Date: " + case4.hearingDate);
System.out.println("Status: " + case4.status);
System.out.println("Case Value: " + case4.caseValue);
System.out.println();

CourtCase case5 = new CourtCase();
case5.caseId = 205;
case5.caseType = "Civil";
case5.plaintiff = "Green Energy Ltd.";
case5.defendant = "Sunshine Corp.";
case5.courtName = "District Court";
case5.judgeName = "Judge Lee";
case5.filingDate = "2024-03-10";
case5.hearingDate = "2024-08-20";
case5.status = "Pending";
case5.caseValue = 500000.00;
System.out.println("Case 5: ");
System.out.println("Case ID: " + case5.caseId);
System.out.println("Case Type: " + case5.caseType);
System.out.println("Plaintiff: " + case5.plaintiff);
System.out.println("Defendant: " + case5.defendant);
System.out.println("Court Name: " + case5.courtName);
System.out.println("Judge Name: " + case5.judgeName);
System.out.println("Filing Date: " + case5.filingDate);
System.out.println("Hearing Date: " + case5.hearingDate);
System.out.println("Status: " + case5.status);
System.out.println("Case Value: " + case5.caseValue);
System.out.println();

CourtCase case6 = new CourtCase();
case6.caseId = 206;
case6.caseType = "Family";
case6.plaintiff = "Jessica White";
case6.defendant = "David White";
case6.courtName = "Family Court";
case6.judgeName = "Judge Collins";
case6.filingDate = "2023-10-10";
case6.hearingDate = "2024-02-25";
case6.status = "Closed";
case6.caseValue = 0.0;
System.out.println("Case 6: ");
System.out.println("Case ID: " + case6.caseId);
System.out.println("Case Type: " + case6.caseType);
System.out.println("Plaintiff: " + case6.plaintiff);
System.out.println("Defendant: " + case6.defendant);
System.out.println("Court Name: " + case6.courtName);
System.out.println("Judge Name: " + case6.judgeName);
System.out.println("Filing Date: " + case6.filingDate);
System.out.println("Hearing Date: " + case6.hearingDate);
System.out.println("Status: " + case6.status);
System.out.println("Case Value: " + case6.caseValue);
System.out.println();

CourtCase case7 = new CourtCase();
case7.caseId = 207;
case7.caseType = "Criminal";
case7.plaintiff = "State of Florida";
case7.defendant = "Carlos Rivera";
case7.courtName = "Florida Criminal Court";
case7.judgeName = "Judge Martinez";
case7.filingDate = "2024-04-12";
case7.hearingDate = "2024-09-01";
case7.status = "Pending";
case7.caseValue = 0.0;
System.out.println("Case 7: ");
System.out.println("Case ID: " + case7.caseId);
System.out.println("Case Type: " + case7.caseType);
System.out.println("Plaintiff: " + case7.plaintiff);
System.out.println("Defendant: " + case7.defendant);
System.out.println("Court Name: " + case7.courtName);
System.out.println("Judge Name: " + case7.judgeName);
System.out.println("Filing Date: " + case7.filingDate);
System.out.println("Hearing Date: " + case7.hearingDate);
System.out.println("Status: " + case7.status);
System.out.println("Case Value: " + case7.caseValue);
System.out.println();

CourtCase case8 = new CourtCase();
case8.caseId = 208;
case8.caseType = "Civil";
case8.plaintiff = "Tech Innovations";
case8.defendant = "XYZ Inc.";
case8.courtName = "District Court";
case8.judgeName = "Judge Patel";
case8.filingDate = "2024-05-05";
case8.hearingDate = "2024-10-10";
case8.status = "Ongoing";
case8.caseValue = 1000000.00;
System.out.println("Case 8: ");
System.out.println("Case ID: " + case8.caseId);
System.out.println("Case Type: " + case8.caseType);
System.out.println("Plaintiff: " + case8.plaintiff);
System.out.println("Defendant: " + case8.defendant);
System.out.println("Court Name: " + case8.courtName);
System.out.println("Judge Name: " + case8.judgeName);
System.out.println("Filing Date: " + case8.filingDate);
System.out.println("Hearing Date: " + case8.hearingDate);
System.out.println("Status: " + case8.status);
System.out.println("Case Value: " + case8.caseValue);
System.out.println();

CourtCase case9 = new CourtCase();
case9.caseId = 209;
case9.caseType = "Family";
case9.plaintiff = "Rachel Green";
case9.defendant = "Ross Geller";
case9.courtName = "Family Court";
case9.judgeName = "Judge Thompson";
case9.filingDate = "2023-09-20";
case9.hearingDate = "2024-01-15";
case9.status = "Closed";
case9.caseValue = 0.0;
System.out.println("Case 9: ");
System.out.println("Case ID: " + case9.caseId);
System.out.println("Case Type: " + case9.caseType);
System.out.println("Plaintiff: " + case9.plaintiff);
System.out.println("Defendant: " + case9.defendant);
System.out.println("Court Name: " + case9.courtName);
System.out.println("Judge Name: " + case9.judgeName);
System.out.println("Filing Date: " + case9.filingDate);
System.out.println("Hearing Date: " + case9.hearingDate);
System.out.println("Status: " + case9.status);
System.out.println("Case Value: " + case9.caseValue);
System.out.println();

CourtCase case10 = new CourtCase();
case10.caseId = 210;
case10.caseType = "Criminal";
case10.plaintiff = "State of New York";
case10.defendant = "Anna Taylor";
case10.courtName = "New York Criminal Court";
case10.judgeName = "Judge Johnson";
case10.filingDate = "2024-02-28";
case10.hearingDate = "2024-07-12";
case10.status = "Pending";
case10.caseValue = 0.0;
System.out.println("Case 10: ");
System.out.println("Case ID: " + case10.caseId);
System.out.println("Case Type: " + case10.caseType);
System.out.println("Plaintiff: " + case10.plaintiff);
System.out.println("Defendant: " + case10.defendant);
System.out.println("Court Name: " + case10.courtName);
System.out.println("Judge Name: " + case10.judgeName);
System.out.println("Filing Date: " + case10.filingDate);
System.out.println("Hearing Date: " + case10.hearingDate);
System.out.println("Status: " + case10.status);
System.out.println("Case Value: " + case10.caseValue);
System.out.println();

CourtCase case11 = new CourtCase();
case11.caseId = 211;
case11.caseType = "Civil";
case11.plaintiff = "John Carter";
case11.defendant = "Omega Ltd.";
case11.courtName = "District Court";
case11.judgeName = "Judge Davis";
case11.filingDate = "2024-03-15";
case11.hearingDate = "2024-08-05";
case11.status = "Ongoing";
case11.caseValue = 750000.00;
System.out.println("Case 11: ");
System.out.println("Case ID: " + case11.caseId);
System.out.println("Case Type: " + case11.caseType);
System.out.println("Plaintiff: " + case11.plaintiff);
System.out.println("Defendant: " + case11.defendant);
System.out.println("Court Name: " + case11.courtName);
System.out.println("Judge Name: " + case11.judgeName);
System.out.println("Filing Date: " + case11.filingDate);
System.out.println("Hearing Date: " + case11.hearingDate);
System.out.println("Status: " + case11.status);
System.out.println("Case Value: " + case11.caseValue);
System.out.println();

CourtCase case12 = new CourtCase();
case12.caseId = 212;
case12.caseType = "Family";
case12.plaintiff = "Emma Wilson";
case12.defendant = "Liam Wilson";
case12.courtName = "Family Court";
case12.judgeName = "Judge Murphy";
case12.filingDate = "2024-01-25";
case12.hearingDate = "2024-05-15";
case12.status = "Pending";
case12.caseValue = 0.0;
System.out.println("Case 12: ");
System.out.println("Case ID: " + case12.caseId);
System.out.println("Case Type: " + case12.caseType);
System.out.println("Plaintiff: " + case12.plaintiff);
System.out.println("Defendant: " + case12.defendant);
System.out.println("Court Name: " + case12.courtName);
System.out.println("Judge Name: " + case12.judgeName);
System.out.println("Filing Date: " + case12.filingDate);
System.out.println("Hearing Date: " + case12.hearingDate);
System.out.println("Status: " + case12.status);
System.out.println("Case Value: " + case12.caseValue);
System.out.println();

CourtCase case13 = new CourtCase();
case13.caseId = 213;
case13.caseType = "Criminal";
case13.plaintiff = "State of Illinois";
case13.defendant = "Henry Clark";
case13.courtName = "Illinois Criminal Court";
case13.judgeName = "Judge Hernandez";
case13.filingDate = "2023-12-30";
case13.hearingDate = "2024-06-01";
case13.status = "Ongoing";
case13.caseValue = 0.0;
System.out.println("Case 13: ");
System.out.println("Case ID: " + case13.caseId);
System.out.println("Case Type: " + case13.caseType);
System.out.println("Plaintiff: " + case13.plaintiff);
System.out.println("Defendant: " + case13.defendant);
System.out.println("Court Name: " + case13.courtName);
System.out.println("Judge Name: " + case13.judgeName);
System.out.println("Filing Date: " + case13.filingDate);
System.out.println("Hearing Date: " + case13.hearingDate);
System.out.println("Status: " + case13.status);
System.out.println("Case Value: " + case13.caseValue);
System.out.println();

CourtCase case14 = new CourtCase();
case14.caseId = 214;
case14.caseType = "Civil";
case14.plaintiff = "Alpha Enterprises";
case14.defendant = "Beta Solutions";
case14.courtName = "District Court";
case14.judgeName = "Judge Robinson";
case14.filingDate = "2024-04-01";
case14.hearingDate = "2024-09-10";
case14.status = "Pending";
case14.caseValue = 300000.00;
System.out.println("Case 14: ");
System.out.println("Case ID: " + case14.caseId);
System.out.println("Case Type: " + case14.caseType);
System.out.println("Plaintiff: " + case14.plaintiff);
System.out.println("Defendant: " + case14.defendant);
System.out.println("Court Name: " + case14.courtName);
System.out.println("Judge Name: " + case14.judgeName);
System.out.println("Filing Date: " + case14.filingDate);
System.out.println("Hearing Date: " + case14.hearingDate);
System.out.println("Status: " + case14.status);
System.out.println("Case Value: " + case14.caseValue);
System.out.println();

CourtCase case15 = new CourtCase();
case15.caseId = 215;
case15.caseType = "Family";
case15.plaintiff = "Olivia Martinez";
case15.defendant = "Ethan Martinez";
case15.courtName = "Family Court";
case15.judgeName = "Judge Clark";
case15.filingDate = "2024-02-20";
case15.hearingDate = "2024-07-05";
case15.status = "Ongoing";
case15.caseValue = 0.0;
System.out.println("Case 15: ");
System.out.println("Case ID: " + case15.caseId);
System.out.println("Case Type: " + case15.caseType);
System.out.println("Plaintiff: " + case15.plaintiff);
System.out.println("Defendant: " + case15.defendant);
System.out.println("Court Name: " + case15.courtName);
System.out.println("Judge Name: " + case15.judgeName);
System.out.println("Filing Date: " + case15.filingDate);
System.out.println("Hearing Date: " + case15.hearingDate);
System.out.println("Status: " + case15.status);
System.out.println("Case Value: " + case15.caseValue);
System.out.println();

CourtCase case16 = new CourtCase();
case16.caseId = 216;
case16.caseType = "Criminal";
case16.plaintiff = "State of Ohio";
case16.defendant = "Sophia Lee";
case16.courtName = "Ohio Criminal Court";
case16.judgeName = "Judge Evans";
case16.filingDate = "2023-11-10";
case16.hearingDate = "2024-04-20";
case16.status = "Closed";
case16.caseValue = 0.0;
System.out.println("Case 16: ");
System.out.println("Case ID: " + case16.caseId);
System.out.println("Case Type: " + case16.caseType);
System.out.println("Plaintiff: " + case16.plaintiff);
System.out.println("Defendant: " + case16.defendant);
System.out.println("Court Name: " + case16.courtName);
System.out.println("Judge Name: " + case16.judgeName);
System.out.println("Filing Date: " + case16.filingDate);
System.out.println("Hearing Date: " + case16.hearingDate);
System.out.println("Status: " + case16.status);
System.out.println("Case Value: " + case16.caseValue);
System.out.println();

CourtCase case17 = new CourtCase();
case17.caseId = 217;
case17.caseType = "Civil";
case17.plaintiff = "Blue Sky Corp.";
case17.defendant = "Red Stone Ltd.";
case17.courtName = "District Court";
case17.judgeName = "Judge King";
case17.filingDate = "2024-03-25";
case17.hearingDate = "2024-08-15";
case17.status = "Ongoing";
case17.caseValue = 450000.00;
System.out.println("Case 17: ");
System.out.println("Case ID: " + case17.caseId);
System.out.println("Case Type: " + case17.caseType);
System.out.println("Plaintiff: " + case17.plaintiff);
System.out.println("Defendant: " + case17.defendant);
System.out.println("Court Name: " + case17.courtName);
System.out.println("Judge Name: " + case17.judgeName);
System.out.println("Filing Date: " + case17.filingDate);
System.out.println("Hearing Date: " + case17.hearingDate);
System.out.println("Status: " + case17.status);
System.out.println("Case Value: " + case17.caseValue);
System.out.println();

CourtCase case18 = new CourtCase();
case18.caseId = 218;
case18.caseType = "Family";
case18.plaintiff = "Mia Davis";
case18.defendant = "Noah Davis";
case18.courtName = "Family Court";
case18.judgeName = "Judge Scott";
case18.filingDate = "2024-01-05";
case18.hearingDate = "2024-06-10";
case18.status = "Pending";
case18.caseValue = 0.0;
System.out.println("Case 18: ");
System.out.println("Case ID: " + case18.caseId);
System.out.println("Case Type: " + case18.caseType);
System.out.println("Plaintiff: " + case18.plaintiff);
System.out.println("Defendant: " + case18.defendant);
System.out.println("Court Name: " + case18.courtName);
System.out.println("Judge Name: " + case18.judgeName);
System.out.println("Filing Date: " + case18.filingDate);
System.out.println("Hearing Date: " + case18.hearingDate);
System.out.println("Status: " + case18.status);
System.out.println("Case Value: " + case18.caseValue);
System.out.println();

CourtCase case19 = new CourtCase();
case19.caseId = 219;
case19.caseType = "Criminal";
case19.plaintiff = "State of Georgia";
case19.defendant = "Evelyn Turner";
case19.courtName = "Georgia Criminal Court";
case19.judgeName = "Judge Baker";
case19.filingDate = "2024-02-15";
case19.hearingDate = "2024-07-20";
case19.status = "Ongoing";
case19.caseValue = 0.0;
System.out.println("Case 19: ");
System.out.println("Case ID: " + case19.caseId);
System.out.println("Case Type: " + case19.caseType);
System.out.println("Plaintiff: " + case19.plaintiff);
System.out.println("Defendant: " + case19.defendant);
System.out.println("Court Name: " + case19.courtName);
System.out.println("Judge Name: " + case19.judgeName);
System.out.println("Filing Date: " + case19.filingDate);
System.out.println("Hearing Date: " + case19.hearingDate);
System.out.println("Status: " + case19.status);
System.out.println("Case Value: " + case19.caseValue);
System.out.println();

CourtCase case20 = new CourtCase();
case20.caseId = 220;
case20.caseType = "Civil";
case20.plaintiff = "Sunrise Ltd.";
case20.defendant = "Moonlight Inc.";
case20.courtName = "District Court";
case20.judgeName = "Judge Wright";
case20.filingDate = "2024-05-15";
case20.hearingDate = "2024-11-05";
case20.status = "Pending";
case20.caseValue = 600000.00;
System.out.println("Case 20: ");
System.out.println("Case ID: " + case20.caseId);
System.out.println("Case Type: " + case20.caseType);
System.out.println("Plaintiff: " + case20.plaintiff);
System.out.println("Defendant: " + case20.defendant);
System.out.println("Court Name: " + case20.courtName);
System.out.println("Judge Name: " + case20.judgeName);
System.out.println("Filing Date: " + case20.filingDate);
System.out.println("Hearing Date: " + case20.hearingDate);
System.out.println("Status: " + case20.status);
System.out.println("Case Value: " + case20.caseValue);
System.out.println();



System.out.pritln("main ended");








}
}