class CrackerRunner{
public static void main(Sring[] crack){
System.out.println("main started");
Crackers cracker1 = new Crackers();
cracker1.crackerId = 101;
cracker1.crackerName = "Sparkle Blast";
cracker1.crackerType = "Sparkler";
cracker1.duration = 30;
cracker1.price = 50.0;
cracker1.isSafe = true;
System.out.println("Cracker 1: ");
System.out.println("Cracker ID: " + cracker1.crackerId);
System.out.println("Cracker Name: " + cracker1.crackerName);
System.out.println("Cracker Type: " + cracker1.crackerType);
System.out.println("Duration (seconds): " + cracker1.duration);
System.out.println("Price (INR): " + cracker1.price);
System.out.println("Is Safe: " + cracker1.isSafe);
System.out.println();

Crackers cracker2 = new Crackers();
cracker2.crackerId = 102;
cracker2.crackerName = "Boomer Thunder";
cracker2.crackerType = "Flower Pot";
cracker2.duration = 45;
cracker2.price = 80.0;
cracker2.isSafe = false;
System.out.println("Cracker 2: ");
System.out.println("Cracker ID: " + cracker2.crackerId);
System.out.println("Cracker Name: " + cracker2.crackerName);
System.out.println("Cracker Type: " + cracker2.crackerType);
System.out.println("Duration (seconds): " + cracker2.duration);
System.out.println("Price (INR): " + cracker2.price);
System.out.println("Is Safe: " + cracker2.isSafe);
System.out.println();

Crackers cracker3 = new Crackers();
cracker3.crackerId = 103;
cracker3.crackerName = "Star Light";
cracker3.crackerType = "Chakra";
cracker3.duration = 60;
cracker3.price = 120.0;
cracker3.isSafe = true;
System.out.println("Cracker 3: ");
System.out.println("Cracker ID: " + cracker3.crackerId);
System.out.println("Cracker Name: " + cracker3.crackerName);
System.out.println("Cracker Type: " + cracker3.crackerType);
System.out.println("Duration (seconds): " + cracker3.duration);
System.out.println("Price (INR): " + cracker3.price);
System.out.println("Is Safe: " + cracker3.isSafe);
System.out.println();

Crackers cracker4 = new Crackers();
cracker4.crackerId = 104;
cracker4.crackerName = "Thunder Clap";
cracker4.crackerType = "Anar";
cracker4.duration = 40;
cracker4.price = 70.0;
cracker4.isSafe = false;
System.out.println("Cracker 4: ");
System.out.println("Cracker ID: " + cracker4.crackerId);
System.out.println("Cracker Name: " + cracker4.crackerName);
System.out.println("Cracker Type: " + cracker4.crackerType);
System.out.println("Duration (seconds): " + cracker4.duration);
System.out.println("Price (INR): " + cracker4.price);
System.out.println("Is Safe: " + cracker4.isSafe);
System.out.println();

Crackers cracker5 = new Crackers();
cracker5.crackerId = 105;
cracker5.crackerName = "Lightning Flash";
cracker5.crackerType = "Chakri";
cracker5.duration = 35;
cracker5.price = 55.0;
cracker5.isSafe = true;
System.out.println("Cracker 5: ");
System.out.println("Cracker ID: " + cracker5.crackerId);
System.out.println("Cracker Name: " + cracker5.crackerName);
System.out.println("Cracker Type: " + cracker5.crackerType);
System.out.println("Duration (seconds): " + cracker5.duration);
System.out.println("Price (INR): " + cracker5.price);
System.out.println("Is Safe: " + cracker5.isSafe);
System.out.println();

Crackers cracker6 = new Crackers();
cracker6.crackerId = 106;
cracker6.crackerName = "Rainbow Wheel";
cracker6.crackerType = "Phooljhadi";
cracker6.duration = 50;
cracker6.price = 90.0;
cracker6.isSafe = true;
System.out.println("Cracker 6: ");
System.out.println("Cracker ID: " + cracker6.crackerId);
System.out.println("Cracker Name: " + cracker6.crackerName);
System.out.println("Cracker Type: " + cracker6.crackerType);
System.out.println("Duration (seconds): " + cracker6.duration);
System.out.println("Price (INR): " + cracker6.price);
System.out.println("Is Safe: " + cracker6.isSafe);
System.out.println();

Crackers cracker7 = new Crackers();
cracker7.crackerId = 107;
cracker7.crackerName = "Fire Star";
cracker7.crackerType = "Flower Pot";
cracker7.duration = 55;
cracker7.price = 100.0;
cracker7.isSafe = false;
System.out.println("Cracker 7: ");
System.out.println("Cracker ID: " + cracker7.crackerId);
System.out.println("Cracker Name: " + cracker7.crackerName);
System.out.println("Cracker Type: " + cracker7.crackerType);
System.out.println("Duration (seconds): " + cracker7.duration);
System.out.println("Price (INR): " + cracker7.price);
System.out.println("Is Safe: " + cracker7.isSafe);
System.out.println();

Crackers cracker8 = new Crackers();
cracker8.crackerId = 108;
cracker8.crackerName = "Golden Spark";
cracker8.crackerType = "Sparkler";
cracker8.duration = 25;
cracker8.price = 45.0;
cracker8.isSafe = true;
System.out.println("Cracker 8: ");
System.out.println("Cracker ID: " + cracker8.crackerId);
System.out.println("Cracker Name: " + cracker8.crackerName);
System.out.println("Cracker Type: " + cracker8.crackerType);
System.out.println("Duration (seconds): " + cracker8.duration);
System.out.println("Price (INR): " + cracker8.price);
System.out.println("Is Safe: " + cracker8.isSafe);
System.out.println();

Crackers cracker9 = new Crackers();
cracker9.crackerId = 109;
cracker9.crackerName = "Silver Ring";
cracker9.crackerType = "Chakri";
cracker9.duration = 60;
cracker9.price = 130.0;
cracker9.isSafe = true;
System.out.println("Cracker 9: ");
System.out.println("Cracker ID: " + cracker9.crackerId);
System.out.println("Cracker Name: " + cracker9.crackerName);
System.out.println("Cracker Type: " + cracker9.crackerType);
System.out.println("Duration (seconds): " + cracker9.duration);
System.out.println("Price (INR): " + cracker9.price);
System.out.println("Is Safe: " + cracker9.isSafe);
System.out.println();

Crackers cracker10 = new Crackers();
cracker10.crackerId = 110;
cracker10.crackerName = "Fire Wheel";
cracker10.crackerType = "Chakra";
cracker10.duration = 50;
cracker10.price = 95.0;
cracker10.isSafe = false;
System.out.println("Cracker 10: ");
System.out.println("Cracker ID: " + cracker10.crackerId);
System.out.println("Cracker Name: " + cracker10.crackerName);
System.out.println("Cracker Type: " + cracker10.crackerType);
System.out.println("Duration (seconds): " + cracker10.duration);
System.out.println("Price (INR): " + cracker10.price);
System.out.println("Is Safe: " + cracker10.isSafe);
System.out.println();

Crackers cracker11 = new Crackers();
cracker11.crackerId = 111;
cracker11.crackerName = "Sparkling Sun";
cracker11.crackerType = "Sparkler";
cracker11.duration = 40;
cracker11.price = 65.0;
cracker11.isSafe = true;
System.out.println("Cracker 11: ");
System.out.println("Cracker ID: " + cracker11.crackerId);
System.out.println("Cracker Name: " + cracker11.crackerName);
System.out.println("Cracker Type: " + cracker11.crackerType);
System.out.println("Duration (seconds): " + cracker11.duration);
System.out.println("Price (INR): " + cracker11.price);
System.out.println("Is Safe: " + cracker11.isSafe);
System.out.println();

Crackers cracker12 = new Crackers();
cracker12.crackerId = 112;
cracker12.crackerName = "Flame Burst";
cracker12.crackerType = "Anar";
cracker12.duration = 35;
cracker12.price = 55.0;
cracker12.isSafe = false;
System.out.println("Cracker 12: ");
System.out.println("Cracker ID: " + cracker12.crackerId);
System.out.println("Cracker Name: " + cracker12.crackerName);
System.out.println("Cracker Type: " + cracker12.crackerType);
System.out.println("Duration (seconds): " + cracker12.duration);
System.out.println("Price (INR): " + cracker12.price);
System.out.println("Is Safe: " + cracker12.isSafe);
System.out.println();

Crackers cracker13 = new Crackers();
cracker13.crackerId = 113;
cracker13.crackerName = "Magic Spark";
cracker13.crackerType = "Phooljhadi";
cracker13.duration = 45;
cracker13.price = 85.0;
cracker13.isSafe = true;
System.out.println("Cracker 13: ");
System.out.println("Cracker ID: " + cracker13.crackerId);
System.out.println("Cracker Name: " + cracker13.crackerName);
System.out.println("Cracker Type: " + cracker13.crackerType);
System.out.println("Duration (seconds): " + cracker13.duration);
System.out.println("Price (INR): " + cracker13.price);
System.out.println("Is Safe: " + cracker13.isSafe);
System.out.println();

Crackers cracker14 = new Crackers();
cracker14.crackerId = 114;
cracker14.crackerName = "Blue Spark";
cracker14.crackerType = "Sparkler";
cracker14.duration = 30;
cracker14.price = 50.0;
cracker14.isSafe = true;
System.out.println("Cracker 14: ");
System.out.println("Cracker ID: " + cracker14.crackerId);
System.out.println("Cracker Name: " + cracker14.crackerName);
System.out.println("Cracker Type: " + cracker14.crackerType);
System.out.println("Duration (seconds): " + cracker14.duration);
System.out.println("Price (INR): " + cracker14.price);
System.out.println("Is Safe: " + cracker14.isSafe);
System.out.println();

Crackers cracker15 = new Crackers();
cracker15.crackerId = 115;
cracker15.crackerName = "Red Glow";
cracker15.crackerType = "Chakra";
cracker15.duration = 55;
cracker15.price = 100.0;
cracker15.isSafe = false;
System.out.println("Cracker 15: ");
System.out.println("Cracker ID: " + cracker15.crackerId);
System.out.println("Cracker Name: " + cracker15.crackerName);
System.out.println("Cracker Type: " + cracker15.crackerType);
System.out.println("Duration (seconds): " + cracker15.duration);
System.out.println("Price (INR): " + cracker15.price);
System.out.println("Is Safe: " + cracker15.isSafe);
System.out.println();

Crackers cracker16 = new Crackers();
cracker16.crackerId = 116;
cracker16.crackerName = "Golden Flame";
cracker16.crackerType = "Flower Pot";
cracker16.duration = 40;
cracker16.price = 70.0;
cracker16.isSafe = true;
System.out.println("Cracker 16: ");
System.out.println("Cracker ID: " + cracker16.crackerId);
System.out.println("Cracker Name: " + cracker16.crackerName);
System.out.println("Cracker Type: " + cracker16.crackerType);
System.out.println("Duration (seconds): " + cracker16.duration);
System.out.println("Price (INR): " + cracker16.price);
System.out.println("Is Safe: " + cracker16.isSafe);
System.out.println();

Crackers cracker17 = new Crackers();
cracker17.crackerId = 117;
cracker17.crackerName = "Silver Shine";
cracker17.crackerType = "Chakri";
cracker17.duration = 60;
cracker17.price = 125.0;
cracker17.isSafe = true;
System.out.println("Cracker 17: ");
System.out.println("Cracker ID: " + cracker17.crackerId);
System.out.println("Cracker Name: " + cracker17.crackerName);
System.out.println("Cracker Type: " + cracker17.crackerType);
System.out.println("Duration (seconds): " + cracker17.duration);
System.out.println("Price (INR): " + cracker17.price);
System.out.println("Is Safe: " + cracker17.isSafe);
System.out.println();

Crackers cracker18 = new Crackers();
cracker18.crackerId = 118;
cracker18.crackerName = "Thunder Strike";
cracker18.crackerType = "Anar";
cracker18.duration = 35;
cracker18.price = 60.0;
cracker18.isSafe = false;
System.out.println("Cracker 18: ");
System.out.println("Cracker ID: " + cracker18.crackerId);
System.out.println("Cracker Name: " + cracker18.crackerName);
System.out.println("Cracker Type: " + cracker18.crackerType);
System.out.println("Duration (seconds): " + cracker18.duration);
System.out.println("Price (INR): " + cracker18.price);
System.out.println("Is Safe: " + cracker18.isSafe);
System.out.println();

Crackers cracker19 = new Crackers();
cracker19.crackerId = 119;
cracker19.crackerName = "Rainbow Spin";
cracker19.crackerType = "Phooljhadi";
cracker19.duration = 50;
cracker19.price = 85.0;
cracker19.isSafe = true;
System.out.println("Cracker 19: ");
System.out.println("Cracker ID: " + cracker19.crackerId);
System.out.println("Cracker Name: " + cracker19.crackerName);
System.out.println("Cracker Type: " + cracker19.crackerType);
System.out.println("Duration (seconds): " + cracker19.duration);
System.out.println("Price (INR): " + cracker19.price);
System.out.println("Is Safe: " + cracker19.isSafe);
System.out.println();

Crackers cracker20 = new Crackers();
cracker20.crackerId = 120;
cracker20.crackerName = "Golden Fire";
cracker20.crackerType = "Sparkler";
cracker20.duration = 30;
cracker20.price = 55.0;
cracker20.isSafe = true;
System.out.println("Cracker 20: ");
System.out.println("Cracker ID: " + cracker20.crackerId);
System.out.println("Cracker Name: " + cracker20.crackerName);
System.out.println("Cracker Type: " + cracker20.crackerType);
System.out.println("Duration (seconds): " + cracker20.duration);
System.out.println("Price (INR): " + cracker20.price);
System.out.println("Is Safe: " + cracker20.isSafe);
System.out.println();

System.out.println("main started");



}
}