class FlowerRunner{
public sttaic void main(String[] flowers){

System.out.println("main started");

Flowers flower1 = new Flowers();
flower1.flowerId = 301;
flower1.flowerName = "Rose";
flower1.color = "Red";
flower1.isFragrant = true;
flower1.averageHeightCm = 50;
flower1.pricePerStem = 15.0;
System.out.println("Flower 1: ");
System.out.println("Flower ID: " + flower1.flowerId);
System.out.println("Flower Name: " + flower1.flowerName);
System.out.println("Color: " + flower1.color);
System.out.println("Is Fragrant: " + flower1.isFragrant);
System.out.println("Average Height (cm): " + flower1.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower1.pricePerStem);
System.out.println();

Flowers flower2 = new Flowers();
flower2.flowerId = 302;
flower2.flowerName = "Jasmine";
flower2.color = "White";
flower2.isFragrant = true;
flower2.averageHeightCm = 40;
flower2.pricePerStem = 20.0;
System.out.println("Flower 2: ");
System.out.println("Flower ID: " + flower2.flowerId);
System.out.println("Flower Name: " + flower2.flowerName);
System.out.println("Color: " + flower2.color);
System.out.println("Is Fragrant: " + flower2.isFragrant);
System.out.println("Average Height (cm): " + flower2.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower2.pricePerStem);
System.out.println();

Flowers flower3 = new Flowers();
flower3.flowerId = 303;
flower3.flowerName = "Sunflower";
flower3.color = "Yellow";
flower3.isFragrant = false;
flower3.averageHeightCm = 150;
flower3.pricePerStem = 25.0;
System.out.println("Flower 3: ");
System.out.println("Flower ID: " + flower3.flowerId);
System.out.println("Flower Name: " + flower3.flowerName);
System.out.println("Color: " + flower3.color);
System.out.println("Is Fragrant: " + flower3.isFragrant);
System.out.println("Average Height (cm): " + flower3.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower3.pricePerStem);
System.out.println();

Flowers flower4 = new Flowers();
flower4.flowerId = 304;
flower4.flowerName = "Lily";
flower4.color = "White";
flower4.isFragrant = true;
flower4.averageHeightCm = 60;
flower4.pricePerStem = 30.0;
System.out.println("Flower 4: ");
System.out.println("Flower ID: " + flower4.flowerId);
System.out.println("Flower Name: " + flower4.flowerName);
System.out.println("Color: " + flower4.color);
System.out.println("Is Fragrant: " + flower4.isFragrant);
System.out.println("Average Height (cm): " + flower4.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower4.pricePerStem);
System.out.println();

Flowers flower5 = new Flowers();
flower5.flowerId = 305;
flower5.flowerName = "Orchid";
flower5.color = "Purple";
flower5.isFragrant = false;
flower5.averageHeightCm = 45;
flower5.pricePerStem = 40.0;
System.out.println("Flower 5: ");
System.out.println("Flower ID: " + flower5.flowerId);
System.out.println("Flower Name: " + flower5.flowerName);
System.out.println("Color: " + flower5.color);
System.out.println("Is Fragrant: " + flower5.isFragrant);
System.out.println("Average Height (cm): " + flower5.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower5.pricePerStem);
System.out.println();

Flowers flower6 = new Flowers();
flower6.flowerId = 306;
flower6.flowerName = "Marigold";
flower6.color = "Orange";
flower6.isFragrant = true;
flower6.averageHeightCm = 55;
flower6.pricePerStem = 10.0;
System.out.println("Flower 6: ");
System.out.println("Flower ID: " + flower6.flowerId);
System.out.println("Flower Name: " + flower6.flowerName);
System.out.println("Color: " + flower6.color);
System.out.println("Is Fragrant: " + flower6.isFragrant);
System.out.println("Average Height (cm): " + flower6.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower6.pricePerStem);
System.out.println();

Flowers flower7 = new Flowers();
flower7.flowerId = 307;
flower7.flowerName = "Tulip";
flower7.color = "Pink";
flower7.isFragrant = true;
flower7.averageHeightCm = 40;
flower7.pricePerStem = 35.0;
System.out.println("Flower 7: ");
System.out.println("Flower ID: " + flower7.flowerId);
System.out.println("Flower Name: " + flower7.flowerName);
System.out.println("Color: " + flower7.color);
System.out.println("Is Fragrant: " + flower7.isFragrant);
System.out.println("Average Height (cm): " + flower7.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower7.pricePerStem);
System.out.println();

Flowers flower8 = new Flowers();
flower8.flowerId = 308;
flower8.flowerName = "Daisy";
flower8.color = "White";
flower8.isFragrant = false;
flower8.averageHeightCm = 35;
flower8.pricePerStem = 12.0;
System.out.println("Flower 8: ");
System.out.println("Flower ID: " + flower8.flowerId);
System.out.println("Flower Name: " + flower8.flowerName);
System.out.println("Color: " + flower8.color);
System.out.println("Is Fragrant: " + flower8.isFragrant);
System.out.println("Average Height (cm): " + flower8.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower8.pricePerStem);
System.out.println();

Flowers flower9 = new Flowers();
flower9.flowerId = 309;
flower9.flowerName = "Carnation";
flower9.color = "Red";
flower9.isFragrant = true;
flower9.averageHeightCm = 45;
flower9.pricePerStem = 22.0;
System.out.println("Flower 9: ");
System.out.println("Flower ID: " + flower9.flowerId);
System.out.println("Flower Name: " + flower9.flowerName);
System.out.println("Color: " + flower9.color);
System.out.println("Is Fragrant: " + flower9.isFragrant);
System.out.println("Average Height (cm): " + flower9.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower9.pricePerStem);
System.out.println();

Flowers flower10 = new Flowers();
flower10.flowerId = 310;
flower10.flowerName = "Chrysanthemum";
flower10.color = "Yellow";
flower10.isFragrant = false;
flower10.averageHeightCm = 50;
flower10.pricePerStem = 18.0;
System.out.println("Flower 10: ");
System.out.println("Flower ID: " + flower10.flowerId);
System.out.println("Flower Name: " + flower10.flowerName);
System.out.println("Color: " + flower10.color);
System.out.println("Is Fragrant: " + flower10.isFragrant);
System.out.println("Average Height (cm): " + flower10.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower10.pricePerStem);
System.out.println();

Flowers flower11 = new Flowers();
flower11.flowerId = 311;
flower11.flowerName = "Lavender";
flower11.color = "Purple";
flower11.isFragrant = true;
flower11.averageHeightCm = 60;
flower11.pricePerStem = 45.0;
System.out.println("Flower 11: ");
System.out.println("Flower ID: " + flower11.flowerId);
System.out.println("Flower Name: " + flower11.flowerName);
System.out.println("Color: " + flower11.color);
System.out.println("Is Fragrant: " + flower11.isFragrant);
System.out.println("Average Height (cm): " + flower11.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower11.pricePerStem);
System.out.println();

Flowers flower12 = new Flowers();
flower12.flowerId = 312;
flower12.flowerName = "Gardenia";
flower12.color = "White";
flower12.isFragrant = true;
flower12.averageHeightCm = 55;
flower12.pricePerStem = 50.0;
System.out.println("Flower 12: ");
System.out.println("Flower ID: " + flower12.flowerId);
System.out.println("Flower Name: " + flower12.flowerName);
System.out.println("Color: " + flower12.color);
System.out.println("Is Fragrant: " + flower12.isFragrant);
System.out.println("Average Height (cm): " + flower12.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower12.pricePerStem);
System.out.println();

Flowers flower13 = new Flowers();
flower13.flowerId = 313;
flower13.flowerName = "Hibiscus";
flower13.color = "Red";
flower13.isFragrant = false;
flower13.averageHeightCm = 70;
flower13.pricePerStem = 20.0;
System.out.println("Flower 13: ");
System.out.println("Flower ID: " + flower13.flowerId);
System.out.println("Flower Name: " + flower13.flowerName);
System.out.println("Color: " + flower13.color);
System.out.println("Is Fragrant: " + flower13.isFragrant);
System.out.println("Average Height (cm): " + flower13.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower13.pricePerStem);
System.out.println();

Flowers flower14 = new Flowers();
flower14.flowerId = 314;
flower14.flowerName = "Peony";
flower14.color = "Pink";
flower14.isFragrant = true;
flower14.averageHeightCm = 60;
flower14.pricePerStem = 60.0;
System.out.println("Flower 14: ");
System.out.println("Flower ID: " + flower14.flowerId);
System.out.println("Flower Name: " + flower14.flowerName);
System.out.println("Color: " + flower14.color);
System.out.println("Is Fragrant: " + flower14.isFragrant);
System.out.println("Average Height (cm): " + flower14.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower14.pricePerStem);
System.out.println();

Flowers flower15 = new Flowers();
flower15.flowerId = 315;
flower15.flowerName = "Daffodil";
flower15.color = "Yellow";
flower15.isFragrant = true;
flower15.averageHeightCm = 45;
flower15.pricePerStem = 30.0;
System.out.println("Flower 15: ");
System.out.println("Flower ID: " + flower15.flowerId);
System.out.println("Flower Name: " + flower15.flowerName);
System.out.println("Color: " + flower15.color);
System.out.println("Is Fragrant: " + flower15.isFragrant);
System.out.println("Average Height (cm): " + flower15.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower15.pricePerStem);
System.out.println();

Flowers flower16 = new Flowers();
flower16.flowerId = 316;
flower16.flowerName = "Gladiolus";
flower16.color = "Red";
flower16.isFragrant = false;
flower16.averageHeightCm = 80;
flower16.pricePerStem = 35.0;
System.out.println("Flower 16: ");
System.out.println("Flower ID: " + flower16.flowerId);
System.out.println("Flower Name: " + flower16.flowerName);
System.out.println("Color: " + flower16.color);
System.out.println("Is Fragrant: " + flower16.isFragrant);
System.out.println("Average Height (cm): " + flower16.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower16.pricePerStem);
System.out.println();

Flowers flower17 = new Flowers();
flower17.flowerId = 317;
flower17.flowerName = "Bluebell";
flower17.color = "Blue";
flower17.isFragrant = true;
flower17.averageHeightCm = 30;
flower17.pricePerStem = 20.0;
System.out.println("Flower 17: ");
System.out.println("Flower ID: " + flower17.flowerId);
System.out.println("Flower Name: " + flower17.flowerName);
System.out.println("Color: " + flower17.color);
System.out.println("Is Fragrant: " + flower17.isFragrant);
System.out.println("Average Height (cm): " + flower17.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower17.pricePerStem);
System.out.println();

Flowers flower18 = new Flowers();
flower18.flowerId = 318;
flower18.flowerName = "Azalea";
flower18.color = "Pink";
flower18.isFragrant = true;
flower18.averageHeightCm = 35;
flower18.pricePerStem = 28.0;
System.out.println("Flower 18: ");
System.out.println("Flower ID: " + flower18.flowerId);
System.out.println("Flower Name: " + flower18.flowerName);
System.out.println("Color: " + flower18.color);
System.out.println("Is Fragrant: " + flower18.isFragrant);
System.out.println("Average Height (cm): " + flower18.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower18.pricePerStem);
System.out.println();

Flowers flower19 = new Flowers();
flower19.flowerId = 319;
flower19.flowerName = "Camellia";
flower19.color = "White";
flower19.isFragrant = false;
flower19.averageHeightCm = 40;
flower19.pricePerStem = 25.0;
System.out.println("Flower 19: ");
System.out.println("Flower ID: " + flower19.flowerId);
System.out.println("Flower Name: " + flower19.flowerName);
System.out.println("Color: " + flower19.color);
System.out.println("Is Fragrant: " + flower19.isFragrant);
System.out.println("Average Height (cm): " + flower19.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower19.pricePerStem);
System.out.println();

Flowers flower20 = new Flowers();
flower20.flowerId = 320;
flower20.flowerName = "Zinnia";
flower20.color = "Orange";
flower20.isFragrant = false;
flower20.averageHeightCm = 50;
flower20.pricePerStem = 18.0;
System.out.println("Flower 20: ");
System.out.println("Flower ID: " + flower20.flowerId);
System.out.println("Flower Name: " + flower20.flowerName);
System.out.println("Color: " + flower20.color);
System.out.println("Is Fragrant: " + flower20.isFragrant);
System.out.println("Average Height (cm): " + flower20.averageHeightCm);
System.out.println("Price per Stem (INR): " + flower20.pricePerStem);
System.out.println();

System.out.println("main ended");


}
}