class ForestSafariRunner {
    public static void main(String[] args) {

        System.out.println("main started");

        ForestSafari s1 = new ForestSafari();
        s1.safariId = 1;
        System.out.println(s1.safariId);
        s1.safariName = "Gir National Park";
        System.out.println(s1.safariName);
        s1.location = "Gujarat";
        System.out.println(s1.location);
        s1.numberOfAnimals = 300;
        System.out.println(s1.numberOfAnimals);
        s1.hasNightSafari = true;
        System.out.println(s1.hasNightSafari);
        s1.ticketPrice = 1500.0;
        System.out.println(s1.ticketPrice);

        ForestSafari s2 = new ForestSafari();
        s2.safariId = 2;
        System.out.println(s2.safariId);
        s2.safariName = "Jim Corbett Safari";
        System.out.println(s2.safariName);
        s2.location = "Uttarakhand";
        System.out.println(s2.location);
        s2.numberOfAnimals = 250;
        System.out.println(s2.numberOfAnimals);
        s2.hasNightSafari = true;
        System.out.println(s2.hasNightSafari);
        s2.ticketPrice = 1200.0;
        System.out.println(s2.ticketPrice);

        ForestSafari s3 = new ForestSafari();
        s3.safariId = 3;
        System.out.println(s3.safariId);
        s3.safariName = "Ranthambore Safari";
        System.out.println(s3.safariName);
        s3.location = "Rajasthan";
        System.out.println(s3.location);
        s3.numberOfAnimals = 200;
        System.out.println(s3.numberOfAnimals);
        s3.hasNightSafari = false;
        System.out.println(s3.hasNightSafari);
        s3.ticketPrice = 1000.0;
        System.out.println(s3.ticketPrice);

        ForestSafari s4 = new ForestSafari();
        s4.safariId = 4;
        System.out.println(s4.safariId);
        s4.safariName = "Kaziranga Safari";
        System.out.println(s4.safariName);
        s4.location = "Assam";
        System.out.println(s4.location);
        s4.numberOfAnimals = 180;
        System.out.println(s4.numberOfAnimals);
        s4.hasNightSafari = true;
        System.out.println(s4.hasNightSafari);
        s4.ticketPrice = 1400.0;
        System.out.println(s4.ticketPrice);

        ForestSafari s5 = new ForestSafari();
        s5.safariId = 5;
        System.out.println(s5.safariId);
        s5.safariName = "Bandhavgarh Safari";
        System.out.println(s5.safariName);
        s5.location = "Madhya Pradesh";
        System.out.println(s5.location);
        s5.numberOfAnimals = 220;
        System.out.println(s5.numberOfAnimals);
        s5.hasNightSafari = true;
        System.out.println(s5.hasNightSafari);
        s5.ticketPrice = 1600.0;
        System.out.println(s5.ticketPrice);

        ForestSafari s6 = new ForestSafari();
        s6.safariId = 6;
        System.out.println(s6.safariId);
        s6.safariName = "Nagarhole Safari";
        System.out.println(s6.safariName);
        s6.location = "Karnataka";
        System.out.println(s6.location);
        s6.numberOfAnimals = 150;
        System.out.println(s6.numberOfAnimals);
        s6.hasNightSafari = false;
        System.out.println(s6.hasNightSafari);
        s6.ticketPrice = 1100.0;
        System.out.println(s6.ticketPrice);

        ForestSafari s7 = new ForestSafari();
        s7.safariId = 7;
        System.out.println(s7.safariId);
        s7.safariName = "Periyar Wildlife Safari";
        System.out.println(s7.safariName);
        s7.location = "Kerala";
        System.out.println(s7.location);
        s7.numberOfAnimals = 100;
        System.out.println(s7.numberOfAnimals);
        s7.hasNightSafari = false;
        System.out.println(s7.hasNightSafari);
        s7.ticketPrice = 800.0;
        System.out.println(s7.ticketPrice);

        ForestSafari s8 = new ForestSafari();
        s8.safariId = 8;
        System.out.println(s8.safariId);
        s8.safariName = "Sundarbans Safari";
        System.out.println(s8.safariName);
        s8.location = "West Bengal";
        System.out.println(s8.location);
        s8.numberOfAnimals = 170;
        System.out.println(s8.numberOfAnimals);
        s8.hasNightSafari = true;
        System.out.println(s8.hasNightSafari);
        s8.ticketPrice = 1300.0;
        System.out.println(s8.ticketPrice);

        ForestSafari s9 = new ForestSafari();
        s9.safariId = 9;
        System.out.println(s9.safariId);
        s9.safariName = "Tadoba Safari";
        System.out.println(s9.safariName);
        s9.location = "Maharashtra";
        System.out.println(s9.location);
        s9.numberOfAnimals = 210;
        System.out.println(s9.numberOfAnimals);
        s9.hasNightSafari = true;
        System.out.println(s9.hasNightSafari);
        s9.ticketPrice = 1450.0;
        System.out.println(s9.ticketPrice);

        ForestSafari s10 = new ForestSafari();
        s10.safariId = 10;
        System.out.println(s10.safariId);
        s10.safariName = "Satpura Safari";
        System.out.println(s10.safariName);
        s10.location = "Madhya Pradesh";
        System.out.println(s10.location);
        s10.numberOfAnimals = 120;
        System.out.println(s10.numberOfAnimals);
        s10.hasNightSafari = false;
        System.out.println(s10.hasNightSafari);
        s10.ticketPrice = 900.0;
        System.out.println(s10.ticketPrice);

        ForestSafari s11 = new ForestSafari();
        s11.safariId = 11;
        System.out.println(s11.safariId);
        s11.safariName = "Pench Safari";
        System.out.println(s11.safariName);
        s11.location = "Madhya Pradesh";
        System.out.println(s11.location);
        s11.numberOfAnimals = 190;
        System.out.println(s11.numberOfAnimals);
        s11.hasNightSafari = true;
        System.out.println(s11.hasNightSafari);
        s11.ticketPrice = 1250.0;
        System.out.println(s11.ticketPrice);

        ForestSafari s12 = new ForestSafari();
        s12.safariId = 12;
        System.out.println(s12.safariId);
        s12.safariName = "Kanha Safari";
        System.out.println(s12.safariName);
        s12.location = "Madhya Pradesh";
        System.out.println(s12.location);
        s12.numberOfAnimals = 230;
        System.out.println(s12.numberOfAnimals);
        s12.hasNightSafari = true;
        System.out.println(s12.hasNightSafari);
        s12.ticketPrice = 1550.0;
        System.out.println(s12.ticketPrice);

        ForestSafari s13 = new ForestSafari();
        s13.safariId = 13;
        System.out.println(s13.safariId);
        s13.safariName = "Mudumalai Safari";
        System.out.println(s13.safariName);
        s13.location = "Tamil Nadu";
        System.out.println(s13.location);
        s13.numberOfAnimals = 140;
        System.out.println(s13.numberOfAnimals);
        s13.hasNightSafari = false;
        System.out.println(s13.hasNightSafari);
        s13.ticketPrice = 950.0;
        System.out.println(s13.ticketPrice);

        ForestSafari s14 = new ForestSafari();
        s14.safariId = 14;
        System.out.println(s14.safariId);
        s14.safariName = "Anamalai Safari";
        System.out.println(s14.safariName);
        s14.location = "Tamil Nadu";
        System.out.println(s14.location);
        s14.numberOfAnimals = 160;
        System.out.println(s14.numberOfAnimals);
        s14.hasNightSafari = false;
        System.out.println(s14.hasNightSafari);
        s14.ticketPrice = 1000.0;
        System.out.println(s14.ticketPrice);

        ForestSafari s15 = new ForestSafari();
        s15.safariId = 15;
        System.out.println(s15.safariId);
        s15.safariName = "Manas Safari";
        System.out.println(s15.safariName);
        s15.location = "Assam";
        System.out.println(s15.location);
        s15.numberOfAnimals = 180;
        System.out.println(s15.numberOfAnimals);
        s15.hasNightSafari = true;
        System.out.println(s15.hasNightSafari);
        s15.ticketPrice = 1350.0;
        System.out.println(s15.ticketPrice);

        ForestSafari s16 = new ForestSafari();
        s16.safariId = 16;
        System.out.println(s16.safariId);
        s16.safariName = "Dudhwa Safari";
        System.out.println(s16.safariName);
        s16.location = "Uttar Pradesh";
        System.out.println(s16.location);
        s16.numberOfAnimals = 150;
        System.out.println(s16.numberOfAnimals);
        s16.hasNightSafari = false;
        System.out.println(s16.hasNightSafari);
        s16.ticketPrice = 1050.0;
        System.out.println(s16.ticketPrice);

        ForestSafari s17 = new ForestSafari();
        s17.safariId = 17;
        System.out.println(s17.safariId);
        s17.safariName = "Valmiki Safari";
        System.out.println(s17.safariName);
        s17.location = "Bihar";
        System.out.println(s17.location);
        s17.numberOfAnimals = 130;
        System.out.println(s17.numberOfAnimals);
        s17.hasNightSafari = false;
        System.out.println(s17.hasNightSafari);
        s17.ticketPrice = 900.0;
        System.out.println(s17.ticketPrice);

        ForestSafari s18 = new ForestSafari();
        s18.safariId = 18;
        System.out.println(s18.safariId);
        s18.safariName = "Bhitarkanika Safari";
        System.out.println(s18.safariName);
        s18.location = "Odisha";
        System.out.println(s18.location);
        s18.numberOfAnimals = 120;
        System.out.println(s18.numberOfAnimals);
        s18.hasNightSafari = false;
        System.out.println(s18.hasNightSafari);
        s18.ticketPrice = 850.0;
        System.out.println(s18.ticketPrice);

        ForestSafari s19 = new ForestSafari();
        s19.safariId = 19;
        System.out.println(s19.safariId);
        s19.safariName = "Simlipal Safari";
        System.out.println(s19.safariName);
        s19.location = "Odisha";
        System.out.println(s19.location);
        s19.numberOfAnimals = 140;
        System.out.println(s19.numberOfAnimals);
        s19.hasNightSafari = true;
        System.out.println(s19.hasNightSafari);
        s19.ticketPrice = 1150.0;
        System.out.println(s19.ticketPrice);

        ForestSafari s20 = new ForestSafari();
        s20.safariId = 20;
        System.out.println(s20.safariId);
        s20.safariName = "Chinnar Wildlife Safari";
        System.out.println(s20.safariName);
        s20.location = "Kerala";
        System.out.println(s20.location);
        s20.numberOfAnimals = 100;
        System.out.println(s20.numberOfAnimals);
        s20.hasNightSafari = false;
        System.out.println(s20.hasNightSafari);
        s20.ticketPrice = 800.0;
        System.out.println(s20.ticketPrice);

        System.out.println("main ended");
    }
}
