class KingRunner{
public sttaic void main(String[] king){

System.out.println("main started");

King king1 = new King();
king1.kingId = 201;
king1.kingName = "Ashoka";
king1.kingdom = "Maurya Empire";
king1.reignStartYear = -268;
king1.reignEndYear = -232;
king1.isFamous = true;
System.out.println("King 1: ");
System.out.println("King ID: " + king1.kingId);
System.out.println("King Name: " + king1.kingName);
System.out.println("Kingdom: " + king1.kingdom);
System.out.println("Reign Start Year: " + king1.reignStartYear);
System.out.println("Reign End Year: " + king1.reignEndYear);
System.out.println("Is Famous: " + king1.isFamous);
System.out.println();

King king2 = new King();
king2.kingId = 202;
king2.kingName = "Akbar";
king2.kingdom = "Mughal Empire";
king2.reignStartYear = 1556;
king2.reignEndYear = 1605;
king2.isFamous = true;
System.out.println("King 2: ");
System.out.println("King ID: " + king2.kingId);
System.out.println("King Name: " + king2.kingName);
System.out.println("Kingdom: " + king2.kingdom);
System.out.println("Reign Start Year: " + king2.reignStartYear);
System.out.println("Reign End Year: " + king2.reignEndYear);
System.out.println("Is Famous: " + king2.isFamous);
System.out.println();

King king3 = new King();
king3.kingId = 203;
king3.kingName = "Chandragupta";
king3.kingdom = "Maurya Empire";
king3.reignStartYear = -321;
king3.reignEndYear = -297;
king3.isFamous = false;
System.out.println("King 3: ");
System.out.println("King ID: " + king3.kingId);
System.out.println("King Name: " + king3.kingName);
System.out.println("Kingdom: " + king3.kingdom);
System.out.println("Reign Start Year: " + king3.reignStartYear);
System.out.println("Reign End Year: " + king3.reignEndYear);
System.out.println("Is Famous: " + king3.isFamous);
System.out.println();

King king4 = new King();
king4.kingId = 204;
king4.kingName = "Harsha";
king4.kingdom = "Kanauj";
king4.reignStartYear = 606;
king4.reignEndYear = 647;
king4.isFamous = false;
System.out.println("King 4: ");
System.out.println("King ID: " + king4.kingId);
System.out.println("King Name: " + king4.kingName);
System.out.println("Kingdom: " + king4.kingdom);
System.out.println("Reign Start Year: " + king4.reignStartYear);
System.out.println("Reign End Year: " + king4.reignEndYear);
System.out.println("Is Famous: " + king4.isFamous);
System.out.println();

King king5 = new King();
king5.kingId = 205;
king5.kingName = "Raja Raja Chola";
king5.kingdom = "Chola Empire";
king5.reignStartYear = 985;
king5.reignEndYear = 1014;
king5.isFamous = true;
System.out.println("King 5: ");
System.out.println("King ID: " + king5.kingId);
System.out.println("King Name: " + king5.kingName);
System.out.println("Kingdom: " + king5.kingdom);
System.out.println("Reign Start Year: " + king5.reignStartYear);
System.out.println("Reign End Year: " + king5.reignEndYear);
System.out.println("Is Famous: " + king5.isFamous);
System.out.println();

King king6 = new King();
king6.kingId = 206;
king6.kingName = "Prithviraj Chauhan";
king6.kingdom = "Chauhan Dynasty";
king6.reignStartYear = 1178;
king6.reignEndYear = 1192;
king6.isFamous = true;
System.out.println("King 6: ");
System.out.println("King ID: " + king6.kingId);
System.out.println("King Name: " + king6.kingName);
System.out.println("Kingdom: " + king6.kingdom);
System.out.println("Reign Start Year: " + king6.reignStartYear);
System.out.println("Reign End Year: " + king6.reignEndYear);
System.out.println("Is Famous: " + king6.isFamous);
System.out.println();

King king7 = new King();
king7.kingId = 207;
king7.kingName = "Tipu Sultan";
king7.kingdom = "Mysore Kingdom";
king7.reignStartYear = 1782;
king7.reignEndYear = 1799;
king7.isFamous = true;
System.out.println("King 7: ");
System.out.println("King ID: " + king7.kingId);
System.out.println("King Name: " + king7.kingName);
System.out.println("Kingdom: " + king7.kingdom);
System.out.println("Reign Start Year: " + king7.reignStartYear);
System.out.println("Reign End Year: " + king7.reignEndYear);
System.out.println("Is Famous: " + king7.isFamous);
System.out.println();

King king8 = new King();
king8.kingId = 208;
king8.kingName = "Shivaji";
king8.kingdom = "Maratha Empire";
king8.reignStartYear = 1674;
king8.reignEndYear = 1680;
king8.isFamous = true;
System.out.println("King 8: ");
System.out.println("King ID: " + king8.kingId);
System.out.println("King Name: " + king8.kingName);
System.out.println("Kingdom: " + king8.kingdom);
System.out.println("Reign Start Year: " + king8.reignStartYear);
System.out.println("Reign End Year: " + king8.reignEndYear);
System.out.println("Is Famous: " + king8.isFamous);
System.out.println();

King king9 = new King();
king9.kingId = 209;
king9.kingName = "Bahadur Shah Zafar";
king9.kingdom = "Mughal Empire";
king9.reignStartYear = 1837;
king9.reignEndYear = 1857;
king9.isFamous = false;
System.out.println("King 9: ");
System.out.println("King ID: " + king9.kingId);
System.out.println("King Name: " + king9.kingName);
System.out.println("Kingdom: " + king9.kingdom);
System.out.println("Reign Start Year: " + king9.reignStartYear);
System.out.println("Reign End Year: " + king9.reignEndYear);
System.out.println("Is Famous: " + king9.isFamous);
System.out.println();

King king10 = new King();
king10.kingId = 210;
king10.kingName = "Samudragupta";
king10.kingdom = "Gupta Empire";
king10.reignStartYear = 335;
king10.reignEndYear = 375;
king10.isFamous = true;
System.out.println("King 10: ");
System.out.println("King ID: " + king10.kingId);
System.out.println("King Name: " + king10.kingName);
System.out.println("Kingdom: " + king10.kingdom);
System.out.println("Reign Start Year: " + king10.reignStartYear);
System.out.println("Reign End Year: " + king10.reignEndYear);
System.out.println("Is Famous: " + king10.isFamous);
System.out.println();

King king11 = new King();
king11.kingId = 211;
king11.kingName = "Pulakeshin II";
king11.kingdom = "Chalukya Dynasty";
king11.reignStartYear = 610;
king11.reignEndYear = 642;
king11.isFamous = true;
System.out.println("King 11: ");
System.out.println("King ID: " + king11.kingId);
System.out.println("King Name: " + king11.kingName);
System.out.println("Kingdom: " + king11.kingdom);
System.out.println("Reign Start Year: " + king11.reignStartYear);
System.out.println("Reign End Year: " + king11.reignEndYear);
System.out.println("Is Famous: " + king11.isFamous);
System.out.println();

King king12 = new King();
king12.kingId = 212;
king12.kingName = "Rajendra Chola";
king12.kingdom = "Chola Empire";
king12.reignStartYear = 1014;
king12.reignEndYear = 1044;
king12.isFamous = true;
System.out.println("King 12: ");
System.out.println("King ID: " + king12.kingId);
System.out.println("King Name: " + king12.kingName);
System.out.println("Kingdom: " + king12.kingdom);
System.out.println("Reign Start Year: " + king12.reignStartYear);
System.out.println("Reign End Year: " + king12.reignEndYear);
System.out.println("Is Famous: " + king12.isFamous);
System.out.println();

King king13 = new King();
king13.kingId = 213;
king13.kingName = "Samrat Vikramaditya";
king13.kingdom = "Gupta Empire";
king13.reignStartYear = 375;
king13.reignEndYear = 415;
king13.isFamous = true;
System.out.println("King 13: ");
System.out.println("King ID: " + king13.kingId);
System.out.println("King Name: " + king13.kingName);
System.out.println("Kingdom: " + king13.kingdom);
System.out.println("Reign Start Year: " + king13.reignStartYear);
System.out.println("Reign End Year: " + king13.reignEndYear);
System.out.println("Is Famous: " + king13.isFamous);
System.out.println();

King king14 = new King();
king14.kingId = 214;
king14.kingName = "Krishnadevaraya";
king14.kingdom = "Vijayanagara Empire";
king14.reignStartYear = 1509;
king14.reignEndYear = 1529;
king14.isFamous = true;
System.out.println("King 14: ");
System.out.println("King ID: " + king14.kingId);
System.out.println("King Name: " + king14.kingName);
System.out.println("Kingdom: " + king14.kingdom);
System.out.println("Reign Start Year: " + king14.reignStartYear);
System.out.println("Reign End Year: " + king14.reignEndYear);
System.out.println("Is Famous: " + king14.isFamous);
System.out.println();

King king15 = new King();
king15.kingId = 215;
king15.kingName = "Bahadur Shah";
king15.kingdom = "Mughal Empire";
king15.reignStartYear = 1526;
king15.reignEndYear = 1530;
king15.isFamous = false;
System.out.println("King 15: ");
System.out.println("King ID: " + king15.kingId);
System.out.println("King Name: " + king15.kingName);
System.out.println("Kingdom: " + king15.kingdom);
System.out.println("Reign Start Year: " + king15.reignStartYear);
System.out.println("Reign End Year: " + king15.reignEndYear);
System.out.println("Is Famous: " + king15.isFamous);
System.out.println();

King king16 = new King();
king16.kingId = 216;
king16.kingName = "Maharana Pratap";
king16.kingdom = "Mewar Kingdom";
king16.reignStartYear = 1572;
king16.reignEndYear = 1597;
king16.isFamous = true;
System.out.println("King 16: ");
System.out.println("King ID: " + king16.kingId);
System.out.println("King Name: " + king16.kingName);
System.out.println("Kingdom: " + king16.kingdom);
System.out.println("Reign Start Year: " + king16.reignStartYear);
System.out.println("Reign End Year: " + king16.reignEndYear);
System.out.println("Is Famous: " + king16.isFamous);
System.out.println();

King king17 = new King();
king17.kingId = 217;
king17.kingName = "Raja Bhoja";
king17.kingdom = "Paramara Dynasty";
king17.reignStartYear = 1010;
king17.reignEndYear = 1055;
king17.isFamous = true;
System.out.println("King 17: ");
System.out.println("King ID: " + king17.kingId);
System.out.println("King Name: " + king17.kingName);
System.out.println("Kingdom: " + king17.kingdom);
System.out.println("Reign Start Year: " + king17.reignStartYear);
System.out.println("Reign End Year: " + king17.reignEndYear);
System.out.println("Is Famous: " + king17.isFamous);
System.out.println();

King king18 = new King();
king18.kingId = 218;
king18.kingName = "Harshavardhana";
king18.kingdom = "Pushyabhuti Dynasty";
king18.reignStartYear = 606;
king18.reignEndYear = 647;
king18.isFamous = false;
System.out.println("King 18: ");
System.out.println("King ID: " + king18.kingId);
System.out.println("King Name: " + king18.kingName);
System.out.println("Kingdom: " + king18.kingdom);
System.out.println("Reign Start Year: " + king18.reignStartYear);
System.out.println("Reign End Year: " + king18.reignEndYear);
System.out.println("Is Famous: " + king18.isFamous);
System.out.println();

King king19 = new King();
king19.kingId = 219;
king19.kingName = "Raja Harishchandra";
king19.kingdom = "Ikshvaku Dynasty";
king19.reignStartYear = -1300;
king19.reignEndYear = -1275;
king19.isFamous = true;
System.out.println("King 19: ");
System.out.println("King ID: " + king19.kingId);
System.out.println("King Name: " + king19.kingName);
System.out.println("Kingdom: " + king19.kingdom);
System.out.println("Reign Start Year: " + king19.reignStartYear);
System.out.println("Reign End Year: " + king19.reignEndYear);
System.out.println("Is Famous: " + king19.isFamous);
System.out.println();

King king20 = new King();
king20.kingId = 220;
king20.kingName = "Raja Vikramaditya";
king20.kingdom = "Malwa Kingdom";
king20.reignStartYear = -75;
king20.reignEndYear = 25;
king20.isFamous = true;
System.out.println("King 20: ");
System.out.println("King ID: " + king20.kingId);
System.out.println("King Name: " + king20.kingName);
System.out.println("Kingdom: " + king20.kingdom);
System.out.println("Reign Start Year: " + king20.reignStartYear);
System.out.println("Reign End Year: " + king20.reignEndYear);
System.out.println("Is Famous: " + king20.isFamous);
System.out.println();

System.out.println("main ended");


}
}