class PoliceStation{
  static String policeStationName;
  static String area;
  static int pinCode;
  static String location;
  static int staffNo;
  static String flieType;
  static String vehicleColor;
  static String vehicleNo;
  static int ConstableNo;
  static int cellNo;
  static String openingTime;
  static String closedTime;
  static String country ;
  static char code ;
  static long depatmentCode ;
  static String parkingSpace;
  static int controllRoom;
  static  int noOfFIR;
  static String uniformColor;
  public static void main(String policestation[]){
   System.out.println("policeStationName:"+policeStationName);
   System.out.println("area:"+area); 
   System.out.println("pinCode:"+pinCode);
   System.out.println("location:"+location);
   System.out.println(" staffNo:"+ staffNo);
   System.out.println("vehicleColor:"+vehicleColor);
   System.out.println("vehicleNo:"+vehicleNo);
   System.out.println("ConstableNo:"+ConstableNo);
   System.out.println("cellNo:"+cellNo);
   System.out.println("openingTime:"+openingTime);
   System.out.println(" closedTime:"+ closedTime);
   System.out.println(" country:"+ country);
   System.out.println("code:"+code);
   System.out.println("depatmentCode:"+depatmentCode);
   System.out.println("parkingSpace:"+parkingSpace);
   System.out.println("controllRoom:"+controllRoom);
   System.out.println("noOfFIR:"+noOfFIR);
   System.out.println("uniformColor:"+uniformColor);
   
    policeStationName="Hoysala";
    area="Thalagattapura";
    pinCode=560062;
    location="Banglore";
    staffNo=13;
    flieType="criminal";
    vehicleColor="white";
    vehicleNo="KA-3745";
    ConstableNo=7;
    cellNo=4;
   openingTime="10:30";
    closedTime="12:30";
   country = "India";
   code = 'C';
  depatmentCode = 1234567890L;
   parkingSpace="yes";
   controllRoom=5;
   noOfFIR=345;
  uniformColor="brown";
  
   System.out.println("policeStationName:"+policeStationName);
   System.out.println("area:"+area); 
   System.out.println("pinCode:"+pinCode);
   System.out.println("location:"+location);
   System.out.println(" staffNo:"+ staffNo);
   System.out.println("vehicleColor:"+vehicleColor);
   System.out.println("vehicleNo:"+vehicleNo);
   System.out.println("ConstableNo:"+ConstableNo);
   System.out.println("cellNo:"+cellNo);
   System.out.println("openingTime:"+openingTime);
   System.out.println(" closedTime:"+ closedTime);
   System.out.println(" country:"+ country);
   System.out.println("code:"+code);
   System.out.println("depatmentCode:"+depatmentCode);
   System.out.println("parkingSpace:"+parkingSpace);
   System.out.println("controllRoom:"+controllRoom);
   System.out.println("noOfFIR:"+noOfFIR);
   System.out.println("uniformColor:"+uniformColor);
  }
}