class RotiRunner {

    public static void main(String[] args) {
        Roti r1 = new Roti();
        r1.rotiId = 1;
        r1.type = "Wheat";
        r1.diameterCm = 15.5;
        r1.calories = 120;
        r1.isWholeWheat = true;
        r1.pricePerPiece = 10.0;
        System.out.println(r1.rotiId);
        System.out.println(r1.type);
        System.out.println(r1.diameterCm);
        System.out.println(r1.calories);
        System.out.println(r1.isWholeWheat);
        System.out.println(r1.pricePerPiece);

        Roti r2 = new Roti();
        r2.rotiId = 2;
        r2.type = "Multigrain";
        r2.diameterCm = 16.0;
        r2.calories = 110;
        r2.isWholeWheat = false;
        r2.pricePerPiece = 12.5;
        System.out.println(r2.rotiId);
        System.out.println(r2.type);
        System.out.println(r2.diameterCm);
        System.out.println(r2.calories);
        System.out.println(r2.isWholeWheat);
        System.out.println(r2.pricePerPiece);

        Roti r3 = new Roti();
        r3.rotiId = 3;
        r3.type = "Bajra";
        r3.diameterCm = 14.0;
        r3.calories = 130;
        r3.isWholeWheat = true;
        r3.pricePerPiece = 11.0;
        System.out.println(r3.rotiId);
        System.out.println(r3.type);
        System.out.println(r3.diameterCm);
        System.out.println(r3.calories);
        System.out.println(r3.isWholeWheat);
        System.out.println(r3.pricePerPiece);

        Roti r4 = new Roti();
        r4.rotiId = 4;
        r4.type = "Jowar";
        r4.diameterCm = 13.5;
        r4.calories = 125;
        r4.isWholeWheat = false;
        r4.pricePerPiece = 9.5;
        System.out.println(r4.rotiId);
        System.out.println(r4.type);
        System.out.println(r4.diameterCm);
        System.out.println(r4.calories);
        System.out.println(r4.isWholeWheat);
        System.out.println(r4.pricePerPiece);

        Roti r5 = new Roti();
        r5.rotiId = 5;
        r5.type = "Ragi";
        r5.diameterCm = 12.0;
        r5.calories = 100;
        r5.isWholeWheat = true;
        r5.pricePerPiece = 8.0;
        System.out.println(r5.rotiId);
        System.out.println(r5.type);
        System.out.println(r5.diameterCm);
        System.out.println(r5.calories);
        System.out.println(r5.isWholeWheat);
        System.out.println(r5.pricePerPiece);
		
		        Roti r6 = new Roti();
        r6.rotiId = 6;
        r6.type = "Maize";
        r6.diameterCm = 14.5;
        r6.calories = 105;
        r6.isWholeWheat = false;
        r6.pricePerPiece = 9.0;
        System.out.println(r6.rotiId);
        System.out.println(r6.type);
        System.out.println(r6.diameterCm);
        System.out.println(r6.calories);
        System.out.println(r6.isWholeWheat);
        System.out.println(r6.pricePerPiece);

        Roti r7 = new Roti();
        r7.rotiId = 7;
        r7.type = "Oats";
        r7.diameterCm = 15.0;
        r7.calories = 98;
        r7.isWholeWheat = true;
        r7.pricePerPiece = 10.5;
        System.out.println(r7.rotiId);
        System.out.println(r7.type);
        System.out.println(r7.diameterCm);
        System.out.println(r7.calories);
        System.out.println(r7.isWholeWheat);
        System.out.println(r7.pricePerPiece);

        Roti r8 = new Roti();
        r8.rotiId = 8;
        r8.type = "Quinoa";
        r8.diameterCm = 13.0;
        r8.calories = 115;
        r8.isWholeWheat = true;
        r8.pricePerPiece = 13.0;
        System.out.println(r8.rotiId);
        System.out.println(r8.type);
        System.out.println(r8.diameterCm);
        System.out.println(r8.calories);
        System.out.println(r8.isWholeWheat);
        System.out.println(r8.pricePerPiece);

        Roti r9 = new Roti();
        r9.rotiId = 9;
        r9.type = "Barley";
        r9.diameterCm = 15.0;
        r9.calories = 108;
        r9.isWholeWheat = false;
        r9.pricePerPiece = 9.8;
        System.out.println(r9.rotiId);
        System.out.println(r9.type);
        System.out.println(r9.diameterCm);
        System.out.println(r9.calories);
        System.out.println(r9.isWholeWheat);
        System.out.println(r9.pricePerPiece);

        Roti r10 = new Roti();
        r10.rotiId = 10;
        r10.type = "Amaranth";
        r10.diameterCm = 12.5;
        r10.calories = 95;
        r10.isWholeWheat = true;
        r10.pricePerPiece = 10.2;
        System.out.println(r10.rotiId);
        System.out.println(r10.type);
        System.out.println(r10.diameterCm);
        System.out.println(r10.calories);
        System.out.println(r10.isWholeWheat);
        System.out.println(r10.pricePerPiece);

        Roti r11 = new Roti();
        r11.rotiId = 11;
        r11.type = "Wheat";
        r11.diameterCm = 14.8;
        r11.calories = 117;
        r11.isWholeWheat = true;
        r11.pricePerPiece = 10.0;
        System.out.println(r11.rotiId);
        System.out.println(r11.type);
        System.out.println(r11.diameterCm);
        System.out.println(r11.calories);
        System.out.println(r11.isWholeWheat);
        System.out.println(r11.pricePerPiece);

        Roti r12 = new Roti();
        r12.rotiId = 12;
        r12.type = "Sorghum";
        r12.diameterCm = 13.2;
        r12.calories = 102;
        r12.isWholeWheat = false;
        r12.pricePerPiece = 9.3;
        System.out.println(r12.rotiId);
        System.out.println(r12.type);
        System.out.println(r12.diameterCm);
        System.out.println(r12.calories);
        System.out.println(r12.isWholeWheat);
        System.out.println(r12.pricePerPiece);

        Roti r13 = new Roti();
        r13.rotiId = 13;
        r13.type = "Multigrain";
        r13.diameterCm = 15.6;
        r13.calories = 118;
        r13.isWholeWheat = true;
        r13.pricePerPiece = 11.7;
        System.out.println(r13.rotiId);
        System.out.println(r13.type);
        System.out.println(r13.diameterCm);
        System.out.println(r13.calories);
        System.out.println(r13.isWholeWheat);
        System.out.println(r13.pricePerPiece);

        Roti r14 = new Roti();
        r14.rotiId = 14;
        r14.type = "Ragi";
        r14.diameterCm = 12.3;
        r14.calories = 96;
        r14.isWholeWheat = true;
        r14.pricePerPiece = 8.9;
        System.out.println(r14.rotiId);
        System.out.println(r14.type);
        System.out.println(r14.diameterCm);
        System.out.println(r14.calories);
        System.out.println(r14.isWholeWheat);
        System.out.println(r14.pricePerPiece);

        Roti r15 = new Roti();
        r15.rotiId = 15;
        r15.type = "Bajra";
        r15.diameterCm = 14.4;
        r15.calories = 112;
        r15.isWholeWheat = false;
        r15.pricePerPiece = 10.4;
        System.out.println(r15.rotiId);
        System.out.println(r15.type);
        System.out.println(r15.diameterCm);
        System.out.println(r15.calories);
        System.out.println(r15.isWholeWheat);
        System.out.println(r15.pricePerPiece);

        Roti r16 = new Roti();
        r16.rotiId = 16;
        r16.type = "Wheat";
        r16.diameterCm = 16.5;
        r16.calories = 122;
        r16.isWholeWheat = true;
        r16.pricePerPiece = 11.0;
        System.out.println(r16.rotiId);
        System.out.println(r16.type);
        System.out.println(r16.diameterCm);
        System.out.println(r16.calories);
        System.out.println(r16.isWholeWheat);
        System.out.println(r16.pricePerPiece);

        Roti r17 = new Roti();
        r17.rotiId = 17;
        r17.type = "Maize";
        r17.diameterCm = 13.9;
        r17.calories = 106;
        r17.isWholeWheat = false;
        r17.pricePerPiece = 9.1;
        System.out.println(r17.rotiId);
        System.out.println(r17.type);
        System.out.println(r17.diameterCm);
        System.out.println(r17.calories);
        System.out.println(r17.isWholeWheat);
        System.out.println(r17.pricePerPiece);

        Roti r18 = new Roti();
        r18.rotiId = 18;
        r18.type = "Jowar";
        r18.diameterCm = 12.8;
        r18.calories = 101;
        r18.isWholeWheat = true;
        r18.pricePerPiece = 9.6;
        System.out.println(r18.rotiId);
        System.out.println(r18.type);
        System.out.println(r18.diameterCm);
        System.out.println(r18.calories);
        System.out.println(r18.isWholeWheat);
        System.out.println(r18.pricePerPiece);

        Roti r19 = new Roti();
        r19.rotiId = 19;
        r19.type = "Multigrain";
        r19.diameterCm = 14.7;
        r19.calories = 119;
        r19.isWholeWheat = true;
        r19.pricePerPiece = 12.0;
        System.out.println(r19.rotiId);
        System.out.println(r19.type);
        System.out.println(r19.diameterCm);
        System.out.println(r19.calories);
        System.out.println(r19.isWholeWheat);
        System.out.println(r19.pricePerPiece);

        Roti r20 = new Roti();
        r20.rotiId = 20;
        r20.type = "Wheat";
        r20.diameterCm = 15.9;
        r20.calories = 123;
        r20.isWholeWheat = true;
        r20.pricePerPiece = 10.8;
        System.out.println(r20.rotiId);
        System.out.println(r20.type);
        System.out.println(r20.diameterCm);
        System.out.println(r20.calories);
        System.out.println(r20.isWholeWheat);
        System.out.println(r20.pricePerPiece);

 
    }
}