class VideoGames {
    static int gameId ;
    static String name ;
    static String brand ;
    static String category ;
    static boolean isMultiplayer ;
    static float price;
    static double rating ;
    static char ageGroup ;
    static long serialNumber;
    static String developer ;
    static boolean vrSupported ;
    static short storageGB ;
    static byte usbPorts ;
    static String releaseDate ;
    static boolean hasWifi ;
    static String processor ;
    static boolean parentalControl ;
    static String supportedFormats ;
    static String resolution ;
    static String platform ;

    public static void main(String[] args) {
        System.out.println("game id: " + gameId);
        System.out.println("name: " + name);
        System.out.println("brand: " + brand);
        System.out.println("category: " + category);
        System.out.println("is multiplayer: " + isMultiplayer);
        System.out.println("price: " + price);
        System.out.println("rating: " + rating);
        System.out.println("age group: " + ageGroup);
        System.out.println("serial number: " + serialNumber);
        System.out.println("developer: " + developer);
        System.out.println("vr supported: " + vrSupported);
        System.out.println("storage (gb): " + storageGB);
        System.out.println("usb ports: " + usbPorts);
        System.out.println("release date: " + releaseDate);
        System.out.println("has wifi: " + hasWifi);
        System.out.println("processor: " + processor);
        System.out.println("parental control: " + parentalControl);
        System.out.println("supported formats: " + supportedFormats);
        System.out.println("resolution: " + resolution);
        System.out.println("platform: " + platform);
		
		
	 gameId = 14;
    name = "PlayStation 5";
   brand = "Sony";
   category = "Console";
     isMultiplayer = true;
   price = 49999.99f;
    rating = 4.8;
   ageGroup = 'T';
 serialNumber = 1234567890L;
   developer = "Sony Interactive";
     vrSupported = true;
    storageGB = 825;
   usbPorts = 2;
    releaseDate = "2020-11-12";
    hasWifi = true;
   processor = "8-core AMD Zen 2";
    parentalControl = true;
    supportedFormats = "Disc/Digital";
    resolution = "4K";
     platform = "Console";
        System.out.println("game id: " + gameId);
        System.out.println("name: " + name);
        System.out.println("brand: " + brand);
        System.out.println("category: " + category);
        System.out.println("is multiplayer: " + isMultiplayer);
        System.out.println("price: " + price);
        System.out.println("rating: " + rating);
        System.out.println("age group: " + ageGroup);
        System.out.println("serial number: " + serialNumber);
        System.out.println("developer: " + developer);
        System.out.println("vr supported: " + vrSupported);
        System.out.println("storage (gb): " + storageGB);
        System.out.println("usb ports: " + usbPorts);
        System.out.println("release date: " + releaseDate);
        System.out.println("has wifi: " + hasWifi);
        System.out.println("processor: " + processor);
        System.out.println("parental control: " + parentalControl);
        System.out.println("supported formats: " + supportedFormats);
        System.out.println("resolution: " + resolution);
        System.out.println("platform: " + platform);
    }
}j